<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_How to access training recordsLearner I_859be4</name>
   <tag></tag>
   <elementGuidId>f53df0fe-046f-4f75-8149-7831007c1881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-eligibility/div/div/app-page-content-loop/app-grey-text-box-sidebar/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d184368b-0f76-4cb2-ad4f-619ee621ca1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>94ecbc94-3c8f-4513-aca5-8bdde7a78287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to access training records?Learner ID &amp; Name on training records The ministry requires either a Learner ID number or full name to look up the eligibility of a learner.The Learner ID is issued by the ministry and is a combination of letters and numbers.The full name only includes the learner''s first and last name.If using name, it must match the name that was submitted to the ministry the last time the learner completed training for a CPO-approved course.Email address/ Phone number/ Postal codeThe ministry also requires a secondary piece of information to validate the learner's identity. It can be any one of the learners: email address, phone number, or postal code.It must match the information that was submitted to the ministry the last time the learner completed training for a CPO-approved course.</value>
      <webElementGuid>a18cc122-85b1-4cdd-8cfb-262e7008cc05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-safety-and-prevention-homepage[@class=&quot;ng-star-inserted&quot;]/app-tabs[@class=&quot;safety-override&quot;]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-training-eligibility[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-3 float-right ng-star-inserted&quot;]/app-page-content-loop[1]/app-grey-text-box-sidebar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;box&quot;]</value>
      <webElementGuid>d173a9a2-b0c7-4faa-b23d-24f709322588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-eligibility/div/div/app-page-content-loop/app-grey-text-box-sidebar/div</value>
      <webElementGuid>780a6d20-439b-4e91-a00f-55bbd83f9d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved training providers'])[1]/following::div[8]</value>
      <webElementGuid>12d68626-6beb-479b-bb19-8f78ee326f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eligibility checker'])[2]/following::div[9]</value>
      <webElementGuid>37625a73-11d7-461c-a54e-7bbeb06d7955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-grey-text-box-sidebar/div</value>
      <webElementGuid>80a6dc4f-e0fb-4569-987c-27b4cf565470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;How to access training records?Learner ID &amp; Name on training records The ministry requires either a Learner ID number or full name to look up the eligibility of a learner.The Learner ID is issued by the ministry and is a combination of letters and numbers.The full name only includes the learner&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;s first and last name.If using name, it must match the name that was submitted to the ministry the last time the learner completed training for a CPO-approved course.Email address/ Phone number/ Postal codeThe ministry also requires a secondary piece of information to validate the learner&quot; , &quot;'&quot; , &quot;s identity. It can be any one of the learners: email address, phone number, or postal code.It must match the information that was submitted to the ministry the last time the learner completed training for a CPO-approved course.&quot;) or . = concat(&quot;How to access training records?Learner ID &amp; Name on training records The ministry requires either a Learner ID number or full name to look up the eligibility of a learner.The Learner ID is issued by the ministry and is a combination of letters and numbers.The full name only includes the learner&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;s first and last name.If using name, it must match the name that was submitted to the ministry the last time the learner completed training for a CPO-approved course.Email address/ Phone number/ Postal codeThe ministry also requires a secondary piece of information to validate the learner&quot; , &quot;'&quot; , &quot;s identity. It can be any one of the learners: email address, phone number, or postal code.It must match the information that was submitted to the ministry the last time the learner completed training for a CPO-approved course.&quot;))]</value>
      <webElementGuid>92bb3e60-899a-4091-981c-e3d98023eee2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
