<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Eligibility checker</name>
   <tag></tag>
   <elementGuidId>ab5c87e2-a196-4c83-a4e4-73b67cd17708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='train-elig-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#train-elig-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ad1a00f8-a9f7-4e81-a184-3ef697829ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>train-elig-title</value>
      <webElementGuid>dedb98db-7ec6-4fb3-b8e8-818f17279742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>824c326d-9665-4b0e-b437-fd3da27d6f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eligibility checker</value>
      <webElementGuid>4a8d4d10-8055-49fb-8009-185cae0056da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;train-elig-title&quot;)</value>
      <webElementGuid>eb344ae4-a5cc-418e-85f9-77e3a421c97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='train-elig-title']</value>
      <webElementGuid>b22ebb4d-1dc8-4b81-80c6-e01d8991e2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-eligibility/div/div/h2</value>
      <webElementGuid>b1407cac-37c2-48b2-af9a-afab446a5d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved training providers'])[1]/following::h2[1]</value>
      <webElementGuid>e059f2e5-cc7a-4ed5-a493-92ec315dd79c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eligibility checker'])[2]/following::h2[1]</value>
      <webElementGuid>75e866c3-42e4-46b2-9090-ced1be617358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access your training records and understand your eligibility for the course you want to take.'])[1]/preceding::h2[1]</value>
      <webElementGuid>591dc684-46f3-4d24-85ee-8a005976e3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter personal details'])[1]/preceding::h2[1]</value>
      <webElementGuid>938ab95d-e539-47ba-aa1c-1799c1135731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>5dca85be-ad86-4dd7-ae4a-cc1a137213d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'train-elig-title' and (text() = 'Eligibility checker' or . = 'Eligibility checker')]</value>
      <webElementGuid>2f1a5114-e67b-4a15-8c04-b2c39fedbbe6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
