<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View details</name>
   <tag></tag>
   <elementGuidId>499a7ff2-7688-4954-ad56-7d47ff0a9b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='triage-button-triage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#triage-button-triage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4af7e95d-edc6-48b3-a24f-3c8781045470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>black-button</value>
      <webElementGuid>3f186af7-3f64-4889-a6d1-31677ee42508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>triage-button-triage</value>
      <webElementGuid>87069bfa-f0e7-4d0a-afb4-d0f67b35e982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details</value>
      <webElementGuid>4ba3c1e4-5c72-48a1-ad4c-75ab97e42955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;triage-button-triage&quot;)</value>
      <webElementGuid>423fcaea-3f0f-4dbc-9c07-dd5e8f184bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='triage-button-triage']</value>
      <webElementGuid>c081cc5b-c9ac-4797-99ed-09f312bec91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-program-details/div/div/app-tabs/div/div[2]/app-tab/div/app-program-overview/div[5]/div/app-approval-card/div/div[2]/div[4]/button</value>
      <webElementGuid>2f9f341d-f086-496a-8c98-ca9ad78dfee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='in 16 days'])[1]/following::button[1]</value>
      <webElementGuid>8f2d1bbc-221e-41a2-9e5e-39c952822540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jan 04, 2023'])[1]/following::button[1]</value>
      <webElementGuid>586d702a-469f-4ab6-a0df-b23d7c588887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESK'])[1]/preceding::button[1]</value>
      <webElementGuid>582e7356-9c66-4cbe-8fd8-3f0c9084285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total deficiencies'])[2]/preceding::button[1]</value>
      <webElementGuid>10280f9f-9964-46f2-9326-bce35ab61677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View details']/parent::*</value>
      <webElementGuid>00edb131-efef-4d1d-85e6-36252656947f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/button</value>
      <webElementGuid>4e848c53-f112-4ba2-bac0-279f28b3ac38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'triage-button-triage' and (text() = 'View details' or . = 'View details')]</value>
      <webElementGuid>ecf67321-6eb3-4c72-a90c-2c702a441870</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
