<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alex IncTRIAGE 2  DaysUnder review by P_526885</name>
   <tag></tag>
   <elementGuidId>9ad7f306-f821-4600-b45d-3a1944cd23c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-program-details/div/div/div/app-page-sub-header/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.subheader.yellow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>264ce74c-7348-4434-88c2-e2e36f18742b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subheader yellow</value>
      <webElementGuid>2c7dd359-cd45-4948-b189-e9ad85d1b7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alex IncTRIAGE 2  DaysUnder review by PRAWAH-10052</value>
      <webElementGuid>11fdad78-898d-4d8f-9d86-a3b456188cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-program-details[1]/div[@class=&quot;ontario-row relative&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-12 ontario-large-12 ontario-margin-top-24-! ontario-padding-left-12-!&quot;]/div[1]/app-page-sub-header[1]/div[@class=&quot;subheader yellow&quot;]</value>
      <webElementGuid>d1c89587-5f3b-4548-afc2-069f55454471</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-program-details/div/div/div/app-page-sub-header/div</value>
      <webElementGuid>ce016822-e517-4ad2-b71b-d062ca1c4fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aleksey Dzhoharidze'])[1]/following::div[4]</value>
      <webElementGuid>84b52213-3553-4f89-8cf0-621551ad38cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessor Portal'])[2]/following::div[7]</value>
      <webElementGuid>479420b0-2f46-4b64-a838-224586ad45de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-page-sub-header/div</value>
      <webElementGuid>46a7d38a-6c21-4970-ac97-bbd97d731047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Alex IncTRIAGE 2  DaysUnder review by PRAWAH-10052' or . = 'Alex IncTRIAGE 2  DaysUnder review by PRAWAH-10052')]</value>
      <webElementGuid>c4655ec9-5e9f-4e7a-a47d-eedc0a30fd41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
