<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_Assessor Portal Aleksey Dzhoharidze</name>
   <tag></tag>
   <elementGuidId>824fa224-ee46-446c-b634-15f57a088d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ontario-header-default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='ontario-header-default']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>43e5ac93-8e40-4e19-aa8d-73946351b228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ontario-header-default</value>
      <webElementGuid>7a644ffa-efa2-4d8f-954f-99810647a705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-header header noprint</value>
      <webElementGuid>387742fb-0a50-4303-a7be-2f97819a3b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Assessor Portal Aleksey Dzhoharidze</value>
      <webElementGuid>dbabe9b1-6400-4e50-baea-f69750b12ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ontario-header-default&quot;)</value>
      <webElementGuid>9f928323-ce2c-4075-bd57-9a0296e56117</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//header[@id='ontario-header-default']</value>
      <webElementGuid>694149c2-a60e-454f-893c-6bc87e2f1a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>0baa2518-2565-4635-bf7d-239049e09954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[@id = 'ontario-header-default' and (text() = ' Assessor Portal Aleksey Dzhoharidze' or . = ' Assessor Portal Aleksey Dzhoharidze')]</value>
      <webElementGuid>8055442d-7933-406d-93e2-b8ebae789d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
