<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (10)</name>
   <tag></tag>
   <elementGuidId>a9ec0403-3826-41cf-8e4d-c19f65986398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Worker']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Worker&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>496364e2-39b5-428b-921b-599b73353dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Worker</value>
      <webElementGuid>8888cc6e-1155-4913-9d07-b91b9b25c285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/nav-user-profile.svg</value>
      <webElementGuid>34ac3e57-0dbb-473b-b1df-e2e6543bc9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-main-sidebar[1]/div[@class=&quot;nav-bar&quot;]/ul[1]/li[2]/img[1]</value>
      <webElementGuid>7e9b9860-3b91-4fa0-bcd5-e37eac2ebfa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Worker']</value>
      <webElementGuid>b39a5d37-f5a8-4552-b4ac-46c2aac592c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>f5766556-117d-4a82-b181-51f893668073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Worker' and @src = 'assets/images/nav-user-profile.svg']</value>
      <webElementGuid>26bdbe53-09b3-4a2c-9c9b-cda1caa699e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
