<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Applicant information  Attestations  Pro_8b1ebd</name>
   <tag></tag>
   <elementGuidId>86f1a6b7-5a99-4542-947a-554eff46ebe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-tabs[@id='upper-tabs']/div/div/div/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.ontario-nav-tabs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>82c5f4c5-de8c-445a-9f4c-4371d14cb872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-nav-tabs</value>
      <webElementGuid>87e80805-5156-4b0e-ab30-dea2cfdedac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Applicant information  Attestations  Program documents  Program requirements </value>
      <webElementGuid>65ac1b34-17a4-47dc-92ad-88e283bb9f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upper-tabs&quot;)/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tabs-header&quot;]/div[@class=&quot;ontario-row&quot;]/ul[@class=&quot;ontario-nav-tabs&quot;]</value>
      <webElementGuid>73573896-bc05-470e-af26-4a28e6ee8ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-tabs[@id='upper-tabs']/div/div/div/ul</value>
      <webElementGuid>c3142166-2cef-48cd-bee0-7a78b603b538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program requirements'])[1]/following::ul[1]</value>
      <webElementGuid>8db11a29-fa9c-48c7-afea-7195e2563cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program documents'])[1]/following::ul[1]</value>
      <webElementGuid>0f327d1f-a93b-476a-a39e-f649f7f871f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>5a06044f-9fac-4bf0-b483-2b699641aaa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = ' Applicant information  Attestations  Program documents  Program requirements ' or . = ' Applicant information  Attestations  Program documents  Program requirements ')]</value>
      <webElementGuid>29e6f73a-91ec-4c90-85b6-1ad6b8df747f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
