<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add a worker (2)</name>
   <tag></tag>
   <elementGuidId>1ac1ec65-3fa2-4f69-8cf0-1eb43c39375d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#add-worker-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='add-worker-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f4be7363-543c-4bfb-8040-e8cc6fb5c175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>add-worker-button</value>
      <webElementGuid>c18cea20-98ea-49f9-8291-3feb7d52862d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add a worker</value>
      <webElementGuid>c69e3f4b-0e5e-4783-b51f-da0cdc28a1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-worker-button&quot;)</value>
      <webElementGuid>80b19743-c949-4aec-ac43-2fcfabd2656b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='add-worker-button']</value>
      <webElementGuid>91eb0dae-856d-4639-83f6-eace7aced312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-manage-profiles/div/div/div/app-csr-workers/div/button</value>
      <webElementGuid>81169187-f89d-4d26-b335-5735b8ff8ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employers'])[1]/following::button[1]</value>
      <webElementGuid>ae84d5cd-71ce-428a-8ba0-f114d66f293b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Providers'])[1]/following::button[1]</value>
      <webElementGuid>3581db65-0b6e-4c23-b044-1ee77ef12f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::button[1]</value>
      <webElementGuid>775ad354-25c0-468c-84e1-899cb90f5b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/preceding::button[1]</value>
      <webElementGuid>1f25659c-02cc-48b7-ade3-e8c9644d6993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add a worker']/parent::*</value>
      <webElementGuid>3fab24e8-5923-475a-acc9-32aa27baec9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>624bc805-9c53-460c-a50e-ae82634d0605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'add-worker-button' and (text() = 'Add a worker' or . = 'Add a worker')]</value>
      <webElementGuid>151f7906-a64f-4afe-ac05-063661be2106</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
