<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CD658662</name>
   <tag></tag>
   <elementGuidId>1b0549c9-eb9b-432a-a54e-3a4ea9996ddf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-view-worker/div[2]/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>88d87d04-2a69-4db2-8a5d-3184572cac45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>answer-text</value>
      <webElementGuid>25052c46-81f2-47e7-9671-5b87cdca921e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CD658662 </value>
      <webElementGuid>dcba799f-ec3c-433e-aaaf-b24890578eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-view-worker[1]/div[@class=&quot;ontario-row ontario-margin-top-8-!&quot;]/div[@class=&quot;inline-div ontario-column ontario-small-12 ontario-medium-6 ontario-large-4&quot;]/div[@class=&quot;answer-text&quot;]</value>
      <webElementGuid>0ea46576-c5c0-404d-aaee-ffefb112d744</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-view-worker/div[2]/div[2]/div[2]</value>
      <webElementGuid>79e4bc4d-98b6-4be3-8778-5391079598a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::div[1]</value>
      <webElementGuid>e23d2b14-c28c-4be6-9af8-3f4dfb5f1b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bin3 Jac3'])[1]/following::div[3]</value>
      <webElementGuid>68a79843-cbaf-495e-886d-68b798d73532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email address'])[1]/preceding::div[2]</value>
      <webElementGuid>32fd566f-ac28-4083-a791-004e1f9041fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jacbin@gmail.com'])[1]/preceding::div[3]</value>
      <webElementGuid>b0f75937-0ca6-451b-98f7-728c771b5495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CD658662']/parent::*</value>
      <webElementGuid>dc7d4102-e62f-4672-b9c7-0c07ae26711b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]</value>
      <webElementGuid>0c65e3b1-708f-4668-be3d-0b09f6ffc868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' CD658662 ' or . = ' CD658662 ')]</value>
      <webElementGuid>d21d3bcd-0679-4938-b342-3edb93466ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
