<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Merge worker profileProfile to keepProf_fd8dc6</name>
   <tag></tag>
   <elementGuidId>7670120d-4281-4516-846f-c1e184741ea8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.merge-worker-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-merge-worker/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2152550-5751-4382-8959-df25cff0bb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>merge-worker-container</value>
      <webElementGuid>4db35a96-0366-41bf-b55d-f547d8aec477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merge worker profileProfile to keepProfile to mergeReset Search </value>
      <webElementGuid>7f1292e3-b92e-4071-be0d-12841e4c041f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-merge-worker[1]/div[@class=&quot;merge-worker-container&quot;]</value>
      <webElementGuid>462e2be4-9b10-4f66-a624-139258c1b0cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-merge-worker/div</value>
      <webElementGuid>956c2631-d915-4688-b555-070e5878f67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aleksey Dzhoharidze'])[1]/following::div[1]</value>
      <webElementGuid>1c57c870-4653-4e8b-b60b-fcd1e1b1d243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSR Portal'])[2]/following::div[4]</value>
      <webElementGuid>2459a786-b2df-4533-aebe-f25f7fdc6893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-merge-worker/div</value>
      <webElementGuid>99d765cb-1b24-4b65-ac85-39f39e2d98f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Merge worker profileProfile to keepProfile to mergeReset Search ' or . = 'Merge worker profileProfile to keepProfile to mergeReset Search ')]</value>
      <webElementGuid>04d0d720-a267-45c9-a12b-4dd953a7d1a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
