<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Aleksey Dzhoharidze_rotated back-arrow _18b608 (2)</name>
   <tag></tag>
   <elementGuidId>46dc9db4-e5e7-4554-acdb-9f93562be25b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-add-learner-to-class/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ee94d66-a0c5-4eb1-b5ce-8be6fb84d033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Go back to previous screen</value>
      <webElementGuid>09f391b0-05a5-4d2c-aecf-dd2d10310731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/chevron-down-blue-border.svg</value>
      <webElementGuid>2e679a6c-5b3e-479b-ae5b-678bfcfc1f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11b1b620-2111-4e07-bcc2-5b942078a86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rotated back-arrow ontario-margin-top-8-!</value>
      <webElementGuid>4d7e09f0-e8eb-4854-ae2e-aa5cc9e5165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-add-learner-to-class[1]/div[@class=&quot;ontario-row ontario-margin-top-16-! relative&quot;]/img[@class=&quot;rotated back-arrow ontario-margin-top-8-!&quot;]</value>
      <webElementGuid>a574ab7e-02bf-4f3b-b2c4-4305abbe472f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-add-learner-to-class/div/img</value>
      <webElementGuid>ae1bb971-42b4-443b-ade8-2465551f9511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Go back to previous screen']</value>
      <webElementGuid>b9cf3006-a3e5-4593-b919-aa9bbd506933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>7bfed102-af19-4747-a12e-9f7d3f175d17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Go back to previous screen' and @src = 'assets/images/chevron-down-blue-border.svg']</value>
      <webElementGuid>13431e40-9807-4960-87bc-10f654568456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
