<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Record issued_ontario-checkboxes__inp_42a34b</name>
   <tag></tag>
   <elementGuidId>d49cda3a-794e-46b4-8f2b-6981995fe750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ontario-checkboxes__input.checkbox-option-NaN.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='checkbox'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b13ccbe-a4a1-456c-9c39-83beb170d58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>dd6678c5-499b-4c83-b411-3dd8ff70c6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f3f6426f-0b10-40bf-b5f9-4497d20d8933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-checkboxes__input checkbox-option-NaN ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>251bb613-26c0-44cb-bcb4-27fcbcb729c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZP183802&quot;)/div[@class=&quot;ontario-checkboxes__item&quot;]/input[@class=&quot;ontario-checkboxes__input checkbox-option-NaN ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>95c76e61-a1ba-45ae-83de-664162cf2664</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='checkbox'])[3]</value>
      <webElementGuid>9dc303da-b827-428a-b6e9-e51d4d7be070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-checkbox[@id='ZP183802']/div/input</value>
      <webElementGuid>70fa0f85-d2ba-49f0-84a8-25357b2241e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-checkbox/div/input</value>
      <webElementGuid>48bf3aea-e8f0-4adc-94ac-15e4ae4025cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>cc34af86-7382-4db6-9a70-d19e94b5ecfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
