<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View details (2)</name>
   <tag></tag>
   <elementGuidId>bc666c80-7e5e-4ac7-a71e-e0cf4083195c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#view-details</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='view-details']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>08f4eb85-21d1-4f10-a144-9ced3d71b19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>view-details</value>
      <webElementGuid>4e9d89cd-9bcb-4b21-a03d-3e81b9d280fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-link</value>
      <webElementGuid>6a1de26d-80e5-4bfe-b37b-d74ec5a35ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View details</value>
      <webElementGuid>5d906156-cf6a-4063-b181-b8dd7eea82a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-provider-registration-confirmation[1]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9 float-left&quot;]/app-training-program-list-card[25]/div[@class=&quot;tpListCard inactive&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column subsection ontario-small-12 ontario-padding-bottom-32-!&quot;]/a[@id=&quot;view-details&quot;]</value>
      <webElementGuid>4fa2d56d-9847-42b8-85e0-fa9b828b548a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='view-details']</value>
      <webElementGuid>38bbd47f-7aed-4c92-a015-24390801f671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div[5]/app-training-program-list-card[25]/div/div[4]/div/a</value>
      <webElementGuid>68518bff-cdb6-4e90-9214-f5e59e47e467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View details')]</value>
      <webElementGuid>3d3ae5d3-6aea-4044-8730-6b43e06b465d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nov 16, 2022 to Nov 17, 2022'])[1]/following::a[1]</value>
      <webElementGuid>177c6eec-fc42-4d08-939f-4b0e500173e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active period'])[1]/following::a[1]</value>
      <webElementGuid>e83e3343-f17f-492f-9737-a8e7ec0f15b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working at Heights - Full'])[9]/preceding::a[1]</value>
      <webElementGuid>37e35bd7-16bc-46ba-b41a-d1ab2b6f8ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application review in progress'])[2]/preceding::a[1]</value>
      <webElementGuid>892118aa-b987-4c2d-a5e7-2960db9b86fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View details']/parent::*</value>
      <webElementGuid>7df9b4f5-2816-4a6d-8857-2d1deb4f8666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-training-program-list-card[25]/div/div[4]/div/a</value>
      <webElementGuid>0b5b57fd-7775-4f24-a3f6-33651a8cfac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'view-details' and (text() = 'View details' or . = 'View details')]</value>
      <webElementGuid>f8f8fc8c-a4e1-4501-865e-d3abaa1a116a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
