<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CPO approved programsWorking at heights_0f8598 (1)</name>
   <tag></tag>
   <elementGuidId>04e9c585-7eb1-4742-b499-588d4c72ac38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div[5]/app-page-content-loop/app-grey-text-box-sidebar/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9fc9521-b3c4-4bff-8b28-51e08b375a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>9d4e8537-aea2-45cb-8c31-ef060a34bf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CPO approved programsWorking at heights [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer(CPO) for approval. Read provider standards Read program standards Become an approved providerJoint health and safety committee [JHSC]Certification of certain Joint Health and Safety Committee(JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act(OHSA). Read provider standards Read program standards Become an approved provider</value>
      <webElementGuid>8d5c9a7c-c516-4a5d-9bf2-d33e973535b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-provider-registration-confirmation[1]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-3 float-right&quot;]/app-page-content-loop[1]/app-grey-text-box-sidebar[1]/div[@class=&quot;box&quot;]</value>
      <webElementGuid>592cf137-d441-4810-8ada-ad7bb8198bc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div[5]/app-page-content-loop/app-grey-text-box-sidebar/div</value>
      <webElementGuid>aada5a25-50a5-467a-b6bc-3c4fc7a0d98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-field assessment checklist to be completed'])[4]/following::div[9]</value>
      <webElementGuid>a4bc19f3-e911-466b-b704-67f954778d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[15]/following::div[11]</value>
      <webElementGuid>babc112a-b447-4368-b496-ebbf0cf775d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-grey-text-box-sidebar/div</value>
      <webElementGuid>826c9956-aaf9-4953-9aad-7e5b3a26237c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CPO approved programsWorking at heights [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer(CPO) for approval. Read provider standards Read program standards Become an approved providerJoint health and safety committee [JHSC]Certification of certain Joint Health and Safety Committee(JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act(OHSA). Read provider standards Read program standards Become an approved provider' or . = 'CPO approved programsWorking at heights [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer(CPO) for approval. Read provider standards Read program standards Become an approved providerJoint health and safety committee [JHSC]Certification of certain Joint Health and Safety Committee(JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act(OHSA). Read provider standards Read program standards Become an approved provider')]</value>
      <webElementGuid>9edc3492-bc1f-4099-b930-5a65b6ee5bc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
