<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JHSC - Part OneApplication review in pr_36c4d9</name>
   <tag></tag>
   <elementGuidId>5f7cd959-fd56-44b2-b910-0c022a5f7cf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>79ea6701-c1a5-45d6-a63d-6bcf81a6ec91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-column ontario-small-12 float-left</value>
      <webElementGuid>6e27a9d3-744c-4a24-9cb9-14ba414f1cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JHSC - Part OneApplication review in progressProgram IDJHSC-2014-1-10015Training delivery typeeLearning - EnglishPrimary applicant/ contactjohn doeManager / Senior LeadershipDSAjohn doeManager / Senior LeadershipStatusUnder review by TSA Application submitted on3/25/23, 1:24 PM 9 days agoView details</value>
      <webElementGuid>a2cbea3b-86a6-4104-86bd-f17d71ed286a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-provider-registration-confirmation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9 float-left&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 float-left&quot;]</value>
      <webElementGuid>08b4c7f8-3979-4c67-bdef-6ca9b39b0538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div[2]/div/div[3]</value>
      <webElementGuid>0985e349-2c9e-4c76-a146-5b5ca1ab70bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::div[1]</value>
      <webElementGuid>c070b8d2-5345-4d65-9732-6405d655ae9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/following::div[2]</value>
      <webElementGuid>6d2347ec-0a80-45d4-9f14-0966fe8a3fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>9dd11262-c59d-4afb-a783-8778557d8c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'JHSC - Part OneApplication review in progressProgram IDJHSC-2014-1-10015Training delivery typeeLearning - EnglishPrimary applicant/ contactjohn doeManager / Senior LeadershipDSAjohn doeManager / Senior LeadershipStatusUnder review by TSA Application submitted on3/25/23, 1:24 PM 9 days agoView details' or . = 'JHSC - Part OneApplication review in progressProgram IDJHSC-2014-1-10015Training delivery typeeLearning - EnglishPrimary applicant/ contactjohn doeManager / Senior LeadershipDSAjohn doeManager / Senior LeadershipStatusUnder review by TSA Application submitted on3/25/23, 1:24 PM 9 days agoView details')]</value>
      <webElementGuid>0caf845c-178e-48c6-aac6-f91197f28571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
