<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create your account as a training provi_822e7a</name>
   <tag></tag>
   <elementGuidId>9813db5c-18dd-457d-b1ee-c4f682ca89cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c25d379e-3bdc-4bb9-8dda-4ad2cd8f48ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-container</value>
      <webElementGuid>ffb775eb-237e-49d7-afe0-efd92834e353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create your account as a training provider  Submit training program application for CPO approval  Training program application review and status  Manage approved training programs </value>
      <webElementGuid>3186f85a-8b89-480d-8542-088b3c9147c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-provider-registration-confirmation[1]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9&quot;]/div[@class=&quot;ontario-margin-bottom-48-!&quot;]/div[@class=&quot;text-container&quot;]</value>
      <webElementGuid>b3459aac-078b-4297-9a8d-a17789f43e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/div/div/div[3]/div[2]</value>
      <webElementGuid>d79b1c9e-622d-47a1-abf0-9b52f047af68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Training Programs'])[1]/following::div[4]</value>
      <webElementGuid>918f77d2-d933-4e7a-9bd0-de22a197fb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Johathan Doe'])[1]/following::div[7]</value>
      <webElementGuid>d3b35723-b587-4d9c-b454-32392e2d23d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]</value>
      <webElementGuid>7da72de9-feaf-4c40-98cf-09adc2cd70ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Create your account as a training provider  Submit training program application for CPO approval  Training program application review and status  Manage approved training programs ' or . = ' Create your account as a training provider  Submit training program application for CPO approval  Training program application review and status  Manage approved training programs ')]</value>
      <webElementGuid>8545ec02-2951-4245-a081-f8516967013d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
