<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ABC Training Inc</name>
   <tag></tag>
   <elementGuidId>163ccd5c-639f-4400-9821-1afb27032d6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tp-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tp-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>627ab439-35ba-477c-a878-0f735b1153c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tp-name</value>
      <webElementGuid>3e9985d5-1db2-4224-9646-e6dbf24de7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>866e606f-075e-4cf2-bac8-1e240ba86195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABC Training Inc.</value>
      <webElementGuid>916cd927-5036-4134-a84d-99bcc8a644b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tp-name&quot;)</value>
      <webElementGuid>98a7bb6c-f394-4686-930e-c672e663580b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tp-name']</value>
      <webElementGuid>f6da5d1e-050f-431a-8c9c-f84be8fa5eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/app-training-provider-header/div/div/div/div/div/div</value>
      <webElementGuid>f5b0d305-43ea-4547-afc5-dc2e1fd01304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='français'])[1]/following::div[6]</value>
      <webElementGuid>04cffb31-33ac-4062-8c97-cc60b5761ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FR'])[1]/following::div[6]</value>
      <webElementGuid>f3efdbc8-9890-4cf5-a22d-1de4d0e5a8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Johathan Doe'])[1]/preceding::div[1]</value>
      <webElementGuid>aded1667-f501-42ad-8e1b-b5facfcce0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CPO approved programs'])[1]/preceding::div[4]</value>
      <webElementGuid>555cbd01-2645-416e-9159-6ecac19195ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABC Training Inc.']/parent::*</value>
      <webElementGuid>47526eb9-cbf5-4a98-8fec-95d543b52841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>89632bf7-a82a-4a80-b883-8e919d9befb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tp-name' and (text() = 'ABC Training Inc.' or . = 'ABC Training Inc.')]</value>
      <webElementGuid>5474fcfa-b99c-4035-b357-ab96af57eb0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
