<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Certification</name>
   <tag></tag>
   <elementGuidId>be55ecf3-303b-4e24-ab8a-d35f66019f70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ontario-column.certification-content.ontario-small-12 > h4.border-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-withdraw-program/div/div[2]/div[8]/div/div[2]/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>729fd9c9-cdf9-4e9d-bd40-d4929815a79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-bottom</value>
      <webElementGuid>2f3816cb-81ef-430c-a6d7-4da3e46e07a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Certification</value>
      <webElementGuid>f486f152-4554-4740-8bd4-54bec160db6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-withdraw-program[1]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9 float-norm&quot;]/div[@class=&quot;ontario-row ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-12 ontario-large-11 ontario-margin-top-12-! ontario-margin-bottom-48-!&quot;]/div[@class=&quot;ontario-column certification-content ontario-small-12&quot;]/h4[@class=&quot;border-bottom&quot;]</value>
      <webElementGuid>d4d547ab-feb0-4623-836e-fb60545356d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-withdraw-program/div/div[2]/div[8]/div/div[2]/h4</value>
      <webElementGuid>0d3f074f-4280-46b4-b6bb-ed05ecd41629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe the reason for withdrawal'])[1]/following::h4[1]</value>
      <webElementGuid>bdf99229-f193-45c1-b79c-f0a8c0342356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Withdrawal'])[1]/following::h4[1]</value>
      <webElementGuid>18c1292d-92e8-4184-9310-7c5accb089ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Communication'])[1]/preceding::h4[1]</value>
      <webElementGuid>02ddad6c-7bd8-4ffe-b16f-31f9c4414437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First name'])[2]/preceding::h4[1]</value>
      <webElementGuid>28e71c22-8fdf-4fea-a411-059b9989aa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Certification']/parent::*</value>
      <webElementGuid>cdc3df3c-f3fb-474d-80ea-a530c160528b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h4</value>
      <webElementGuid>48ded001-f269-4c19-a5f5-5b72511eaf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Certification' or . = 'Certification')]</value>
      <webElementGuid>43e88575-5455-4c08-8778-a9996e8914b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
