<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img (2)</name>
   <tag></tag>
   <elementGuidId>af511970-bce7-4ca1-8bd7-c9a4a4deee40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-provider-registration-confirmation/app-main-sidebar/div/ul/li[5]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;'Sidebar.Learners' | translate&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e761a01-36cb-424e-b3ff-951bb46cd6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>'Sidebar.Learners' | translate</value>
      <webElementGuid>6f965d5b-0245-49e1-92f2-f6ad7c98f840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/my-learners.svg</value>
      <webElementGuid>bb11b638-c8eb-461f-a983-7101394c523b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-provider-registration-confirmation[@class=&quot;ng-star-inserted&quot;]/app-main-sidebar[1]/div[@class=&quot;nav-bar ng-star-inserted&quot;]/ul[1]/li[5]/img[1]</value>
      <webElementGuid>236f1a82-199a-4ed2-824e-d14daf0b1614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-provider-registration-confirmation/app-main-sidebar/div/ul/li[5]/img</value>
      <webElementGuid>3f17f440-2b05-4a81-bc5b-d331895e1832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt=&quot;'Sidebar.Learners' | translate&quot;]</value>
      <webElementGuid>757d1636-380e-40d2-b3a2-a119c0b5cb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/img</value>
      <webElementGuid>6853582e-517b-405f-8dd2-2488007a09c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = concat(&quot;'&quot; , &quot;Sidebar.Learners&quot; , &quot;'&quot; , &quot; | translate&quot;) and @src = 'assets/images/my-learners.svg']</value>
      <webElementGuid>db286574-fb85-4d51-9e4c-57ea0e0473e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
