<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_780781</name>
   <tag></tag>
   <elementGuidId>f39d88b5-260b-4ac7-ba24-29b849a383f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='m_6539482804970053851verification-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#m_6539482804970053851verification-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f901a088-1353-41ef-8498-060f21d10637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>m_6539482804970053851verification-code</value>
      <webElementGuid>8fd962dd-6d1c-415c-b43c-8c90e345b9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>780781</value>
      <webElementGuid>6be958a0-71fa-4b2e-89a5-a57b8cc43fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;m_6539482804970053851verification-code&quot;)</value>
      <webElementGuid>2a7963f0-b398-42c6-802f-6a2229799869</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='m_6539482804970053851verification-code']</value>
      <webElementGuid>41e3c7c1-a83d-4565-b643-ab2d0526ea02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':80']/div/div/table/tbody/tr[2]/td/table/tbody/tr[4]/td/span</value>
      <webElementGuid>6068a974-707b-4390-9bfd-5af604e21ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please enter the following code for verification:'])[1]/following::span[1]</value>
      <webElementGuid>78cc6af6-088b-4834-8a5f-676720f73b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::span[1]</value>
      <webElementGuid>b13e5712-e3bb-4808-8503-7142f34952dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The one-time code will expire in 15 minutes or earlier if your session becomes inactive.'])[1]/preceding::span[1]</value>
      <webElementGuid>a2ea708e-538a-4be7-9724-bc28ea2fe0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::span[1]</value>
      <webElementGuid>f7ba39f9-8381-4376-9a32-06fb6d46202a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='780781']/parent::*</value>
      <webElementGuid>30dbc381-456d-4a02-9567-c6a8dc33cb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[4]/td/span</value>
      <webElementGuid>6b082aff-7fad-4bfd-ae6b-020d0e324e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'm_6539482804970053851verification-code' and (text() = '780781' or . = '780781')]</value>
      <webElementGuid>3d706157-bb1a-4e99-8b58-e1a264466915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
