<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Application Preview</name>
   <tag></tag>
   <elementGuidId>2c4bf816-27be-4d87-bd31-cadc8bd8a5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-onboarding-summary/div/div/div[4]/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.border-bottom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>df2e6582-9feb-46cf-907e-969669e9e6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-bottom</value>
      <webElementGuid>a32e9903-ee98-4b05-9d5f-ffb1811655d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Application Preview</value>
      <webElementGuid>3a8aa1bf-e453-4e81-97d4-e82742593cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-onboarding-summary[1]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-12 ontario-large-9 ontario-margin-bottom-32-!&quot;]/div[4]/h3[@class=&quot;border-bottom&quot;]</value>
      <webElementGuid>13814cc4-fc7b-4087-ae5e-733a67aae80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-onboarding-summary/div/div/div[4]/h3</value>
      <webElementGuid>8f36f6be-72d6-452f-96a8-424af56b8aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage and market your training programs'])[1]/following::h3[1]</value>
      <webElementGuid>491c4bf8-545b-47e7-86ef-c722f6d9138a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessor reviews training program application'])[1]/following::h3[1]</value>
      <webElementGuid>a7607ba7-8757-4e47-8bc3-23d85e1ddaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you a signing authority for this training provider account?'])[1]/preceding::h3[1]</value>
      <webElementGuid>ea3d9e43-f1a1-45b7-b607-735f90c58875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/preceding::h3[1]</value>
      <webElementGuid>63636ee8-fd15-4b9d-8beb-7b79a5f1b28c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Application Preview']/parent::*</value>
      <webElementGuid>7ce2aee6-5d6c-4785-8fd0-52514e828764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>c75ceb2b-565e-46eb-a3ce-ca85de4fecca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Application Preview' or . = 'Application Preview')]</value>
      <webElementGuid>d195e263-5bca-4838-959f-1adb35bf3d01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
