<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Course details Program name  Working at_3ceba3</name>
   <tag></tag>
   <elementGuidId>bee910fa-d46b-496b-962e-709b06a392f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-class-enrollment/div/div/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ontario-column.ontario-small-12.ontario-large-4.grey-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aac4883e-c51a-4887-93ae-fe76f6a964c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-column ontario-small-12 ontario-large-4 grey-box</value>
      <webElementGuid>80968cbc-b69c-4a5f-89dd-e7813acad369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Course details Program name  Working at Heights - Full  Training provider ABC Training location 812 - 440 mc murchcy ave s, bramptonl3y0n5 - ON CA Class information  Seats available 23/23 Course fee  Please contact training provider for pricing  Contact us akhil.ca</value>
      <webElementGuid>af549acd-4e91-4030-8920-d7317d3c8df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-class-enrollment[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row relative&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-12 ontario-large-12 ontario-margin-top-48-! ontario-padding-left-12-!&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-4 grey-box&quot;]</value>
      <webElementGuid>3268fcf5-fea3-4263-960e-0c2ac3cceed2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-class-enrollment/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>122fc179-17c4-45dc-a0e5-84682d977e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Message for learner'])[1]/following::div[3]</value>
      <webElementGuid>7afa8b1b-3a01-45ee-8379-7727e0928dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course fees &amp; other administrative work completed.'])[1]/following::div[4]</value>
      <webElementGuid>29e319f7-435a-4b06-9943-56f1344105d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>53c62d80-d256-4ddd-8d7e-6de7206339a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Course details Program name  Working at Heights - Full  Training provider ABC Training location 812 - 440 mc murchcy ave s, bramptonl3y0n5 - ON CA Class information  Seats available 23/23 Course fee  Please contact training provider for pricing  Contact us akhil.ca' or . = 'Course details Program name  Working at Heights - Full  Training provider ABC Training location 812 - 440 mc murchcy ave s, bramptonl3y0n5 - ON CA Class information  Seats available 23/23 Course fee  Please contact training provider for pricing  Contact us akhil.ca')]</value>
      <webElementGuid>04d0b505-c83c-4690-b44e-6790615d11cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
