<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You are eligible</name>
   <tag></tag>
   <elementGuidId>10e6b4c8-52b6-4de2-84f5-ed23d5af7dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#success-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='success-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>501bfe20-3eb6-4617-8409-3200c6c72179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>361b8e19-adea-4a9b-833b-c6397e3c42ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>60713bfb-3b24-4b05-b63e-1d44f9349d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>8ba91bd5-8f79-4abe-b245-b6326c313674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d0083df-7a16-40d3-ac9e-76d1b6399d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>2f17376d-8d68-4d98-83cf-9f6a987da527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>ea41b703-9278-4dac-b9fa-613097f62488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>f50e5936-2c12-461f-a1a1-8e84cc6f6c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6e5a2859-5326-4034-99e2-f6f82c7340db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>f5ae9db9-3edc-4587-abea-9503520dd564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>902a9678-5221-4de1-be50-4ede41f60c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>086abe53-b925-423a-abe5-b9f01993c589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2a8a9a3-8449-4672-8110-2218e5022b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>e3faf668-81e8-40be-b6e7-fc71510a0c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>e36a5940-577e-4c7d-b8e4-bc1311ec79d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>b89e4581-2208-41af-bc2d-0d343f00517a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cfe67970-436c-4a34-9e56-56d22d9559c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>c8830025-bec1-4ada-a136-58e90a691bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>595ca6e4-5d39-401e-a824-d707b7e95279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>8b7bfd2f-3941-4bca-878f-cc63f1f7bb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b8d3f8af-3e37-4f04-8be2-72bfad41b706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>9ec7839e-46af-4072-870c-9bd6fce8e807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>01d7a8e2-e2a8-4423-abe5-fc1c6ea85d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>f9491273-9f14-464c-9820-895173f609e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e6b3841d-a077-4bfd-9d13-0c0978adf2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>5dd0a39c-2722-43a2-bc46-92f006d698af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>1b285175-8c69-4b46-9560-b467c98420d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>5aeef53b-3444-4b88-8238-7a464631f347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25ad08dc-625a-41ab-a76f-16cefb06069a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>success-title</value>
      <webElementGuid>688bf2b3-aa21-474a-8f59-38682c642457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are eligible.</value>
      <webElementGuid>6e502aa4-8f43-4205-baa1-1a3b28b32468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;success-title&quot;)</value>
      <webElementGuid>f444826d-f921-4a88-bb17-f0379550ed15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='success-title']</value>
      <webElementGuid>11573836-a83c-4688-8a09-2be2ed954328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-training-eligibility/div/div[2]/app-tabs/div/div[2]/app-tab[2]/div/form/div/div/app-training-eligibility-result/div/div/div</value>
      <webElementGuid>f48b77e2-88a8-400f-93f6-f0f741d5c5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check Eligibility'])[2]/following::div[3]</value>
      <webElementGuid>45a196e2-8879-45de-8753-ef77fa9f95c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[6]</value>
      <webElementGuid>dfa3206d-e651-409c-99af-80e2c5667161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checked on Aug 4, 2022'])[1]/preceding::div[1]</value>
      <webElementGuid>ddad95f8-16a4-4c70-9727-363d58280bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MLTSD Learner ID'])[1]/preceding::div[2]</value>
      <webElementGuid>c918a5dc-aaaf-4fc2-bee2-02e666bf99b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You are eligible.']/parent::*</value>
      <webElementGuid>82e46b89-d1d8-4603-9872-9e04615024ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-training-eligibility-result/div/div/div</value>
      <webElementGuid>8507bf76-d421-44b9-a62f-99772a1ce3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'success-title' and (text() = 'You are eligible.' or . = 'You are eligible.')]</value>
      <webElementGuid>bee7da9b-5935-4a4a-b3b7-22b0ddbf09e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checked on Aug 3, 2022'])[1]/preceding::div[1]</value>
      <webElementGuid>0965af91-65e6-43cb-9ef5-e045dace4729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checked on Jul 26, 2022'])[1]/preceding::div[1]</value>
      <webElementGuid>f044afec-e76a-4888-b1ac-238cd5646354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checked on Jul 25, 2022'])[1]/preceding::div[1]</value>
      <webElementGuid>1c564e2b-6804-4447-b858-14d74640e295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
