<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Eligibility On_eligibilityOnDate</name>
   <tag></tag>
   <elementGuidId>7a43bc70-bbb1-495f-96df-0d2c6cf8e4b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eligibilityOnDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eligibilityOnDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f26ec60-77cc-4890-bb49-9baef3c0046e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>c4240594-c48d-4626-bf75-98e76262e659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>eligibilityOnDate</value>
      <webElementGuid>ee34430e-8803-493d-a732-bffa935f7b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eligibilityOnDate</value>
      <webElementGuid>c39ff4d0-2d10-4e26-8491-686dfb84c1ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>eligibilityOnDate</value>
      <webElementGuid>7ffbc980-e926-4ef9-acbb-b9dabd7a8f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-input start-date ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>c673b2b0-b087-48ab-9fe8-d9b18767db85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>Mon Jul 25 2022 18:05:35 GMT-0400 (Eastern Daylight Time)</value>
      <webElementGuid>ab03923f-39cf-4cef-8fae-d15a095d64dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eligibilityOnDate&quot;)</value>
      <webElementGuid>e42d269d-eac9-4c60-a9a1-93fc3e04e5d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eligibilityOnDate']</value>
      <webElementGuid>b2b18d40-2c6f-457f-9c95-855e7af9f980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-training-eligibility/div/div[2]/app-tabs/div/div[2]/app-tab[2]/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>f7a590d5-0803-4383-8265-7133461cff47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-tab[2]/div/form/div/div/div/div[2]/input</value>
      <webElementGuid>3c41515b-1bc5-40a7-b925-e1a6c3fd0a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'eligibilityOnDate' and @id = 'eligibilityOnDate']</value>
      <webElementGuid>67b92ccc-f739-4220-9603-0ab1627f46a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
