<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-buttons-0.12246373349209683-0</name>
   <tag></tag>
   <elementGuidId>6956f990-381b-4cbb-8fdf-db074cf54bb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.12246373349209683-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0f03243-be1a-4e53-9e97-d82bce4fbea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>58742ab0-640a-4b35-a534-ca4aee67a421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>f1346b11-92a6-44b8-8556-d7a6e666745e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.12246373349209683-0</value>
      <webElementGuid>85a0a796-2d33-477b-a676-850ea743d7fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.12246373349209683-0</value>
      <webElementGuid>5a0bbf11-4b0d-4786-952f-4a7ad27c8edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>138d05de-bda9-45a8-a447-80a1bd11d9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.12246373349209683-0&quot;)</value>
      <webElementGuid>6dfc4e1a-9652-40c4-bd2b-3ebd6da1f508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0e02de0-40cd-4dc1-a6fb-57b43fe07621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ce4e57d7-f2cb-41bb-894b-69e884f259d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>a576fca2-68f0-4001-8a38-3b1911f88aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.12246373349209683-0</value>
      <webElementGuid>4a6774de-c0c2-414f-902e-6a890baf8f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.12246373349209683-0</value>
      <webElementGuid>48273797-4aa9-44e9-ac79-2dd72b4e6fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cbb7e0ea-1a87-4fcd-ba37-fda242b960cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.12246373349209683-0&quot;)</value>
      <webElementGuid>a3d05d23-56f8-42a6-b31c-f5d93f66a3f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.12246373349209683-0']</value>
      <webElementGuid>6fd680a1-8a46-40c0-9115-c9bc40e0fbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-new-program-application/div/div/div/app-training-provider-attestation/div/div[2]/div[3]/app-tabs/div/div[2]/app-tab[2]/div/div/div[4]/div/div/div/app-radio-button-list[4]/div[2]/input</value>
      <webElementGuid>d00133cb-b015-4ef2-b269-f0f7b8a4111f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/app-radio-button-list[4]/div[2]/input</value>
      <webElementGuid>9095f86e-dc82-4773-b3fa-4cab820488cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.12246373349209683-0' and @name = 'radio-buttons-0.12246373349209683-0']</value>
      <webElementGuid>7419c686-8aef-40df-a27e-d789b7585b1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
