<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-buttons-0.18492451617657513-0</name>
   <tag></tag>
   <elementGuidId>6b979ae2-a060-442a-b5f0-f4f282b21a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.18492451617657513-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5beb6265-ab77-4299-8c2a-f180106ee7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fa89264c-1cd9-45a7-9e75-27398ef7e19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>04a8dc93-2fd3-4184-8a43-f2a13ec1897c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.18492451617657513-0</value>
      <webElementGuid>06cbf430-f5d9-403d-8ed1-75ee617af26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.18492451617657513-0</value>
      <webElementGuid>2737df27-dfe6-4b04-b23f-386a05676cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0a0e8667-4c9f-4ed8-b0c0-a699add0a832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.18492451617657513-0&quot;)</value>
      <webElementGuid>174336fc-fa4a-4e3d-abe8-0f206c3394a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.18492451617657513-0']</value>
      <webElementGuid>2efc640e-fc64-4e2f-8dbf-2481c2360f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-new-program-application/div/div/div/app-training-provider-attestation/div/div[2]/div[3]/app-tabs/div/div[2]/app-tab[2]/div/div/div[2]/div/div/div/app-radio-button-list/div[2]/input</value>
      <webElementGuid>bc81fb26-3db8-4de8-aaae-00734e6d8f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/app-radio-button-list/div[2]/input</value>
      <webElementGuid>a737b165-2051-4230-aa65-38bd0029c7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.18492451617657513-0' and @name = 'radio-buttons-0.18492451617657513-0']</value>
      <webElementGuid>d0e21661-c901-48ec-b902-08319b489735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
