<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-buttons-0.26000574310652746-0</name>
   <tag></tag>
   <elementGuidId>ec07d552-d72d-4a2f-86e2-79c87bc1ff39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.26000574310652746-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0457f26c-9a72-4fb5-bf61-c1cb76221728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>23e10327-2ab5-4165-a2e8-b670c0a543b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>fdd9af99-4151-4bea-9e49-089bc4526c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.26000574310652746-0</value>
      <webElementGuid>cd3f5110-2022-4914-9782-7e221d6cf78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.26000574310652746-0</value>
      <webElementGuid>2ecb222f-a7a4-4e79-b1aa-5c93bba974a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bd63c01f-3457-4db3-9f32-66ce18cc466c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.26000574310652746-0&quot;)</value>
      <webElementGuid>5b7a21a8-8774-43f7-b582-d8e003a5276c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.26000574310652746-0']</value>
      <webElementGuid>44e886b8-f1ac-4861-90e0-43c0fe35d38a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-new-program-application/div/div/div/app-training-provider-attestation/div/div[2]/div[3]/app-tabs/div/div[2]/app-tab/div/div/div[3]/div/div/div/app-radio-button-list[7]/div[2]/input</value>
      <webElementGuid>682b47db-1ff3-4b31-9482-074180b9443c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-radio-button-list[7]/div[2]/input</value>
      <webElementGuid>b347c434-ddad-4b6b-8fe9-054bcd3ab156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.26000574310652746-0' and @name = 'radio-buttons-0.26000574310652746-0']</value>
      <webElementGuid>5b95e064-4a52-4b4e-8369-4a6d115ee23b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
