<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-buttons-0.4079729965177423-0</name>
   <tag></tag>
   <elementGuidId>082c9122-1734-417e-a13d-f37733ffc528</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.4079729965177423-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06fc1ef9-bfc2-4e47-93e5-a484dd27c1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5aa70702-b8d9-4fa7-9f8a-eea1b872f447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>8603e26d-10f8-4a5f-bef0-0adde0a58338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.4079729965177423-0</value>
      <webElementGuid>db71ce97-946a-4066-b063-8103f88250b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.4079729965177423-0</value>
      <webElementGuid>ce9c57ac-aa54-42ca-a5d7-7d0407486752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5239017a-b9ec-49d2-ae48-18267405feb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.4079729965177423-0&quot;)</value>
      <webElementGuid>866ab3f4-60ac-42a7-ab05-286eeff7b7df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.4079729965177423-0']</value>
      <webElementGuid>49ef0cdb-2b74-492e-bcdd-ac3d41156a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-new-program-application/div/div/div/app-training-provider-attestation/div/div[2]/div[3]/app-tabs/div/div[2]/app-tab/div/div/div[3]/div/div/div/app-radio-button-list[2]/div[2]/input</value>
      <webElementGuid>7695a869-7ee6-4d2d-9b31-8ea866cd0523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-radio-button-list[2]/div[2]/input</value>
      <webElementGuid>eaab6c6a-27b5-405d-8748-3f222d38f95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.4079729965177423-0' and @name = 'radio-buttons-0.4079729965177423-0']</value>
      <webElementGuid>4e945a4f-d51c-4842-ba4f-f01e49cbf07a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
