<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First name Last name Email addressPhone_225242</name>
   <tag></tag>
   <elementGuidId>91a9a1b5-40fe-4533-9a65-cab927063061</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-add-member/div/div/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d2b4474-9736-4963-ab0e-98b481996a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content</value>
      <webElementGuid>266448ff-bd23-49fa-a2ea-4a555f8444e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First name Last name Email addressPhone Role Designated signing authorityAdministratorAffiliate administratorInstructorAffiliate instructorOrganizationSelectAdd a new organizationAlex IT Inc</value>
      <webElementGuid>68ae0a73-98b2-402d-8131-5247614f0b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-add-member[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row relative&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-12 ontario-large-12 ontario-margin-top-48-! ontario-padding-left-12-!&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;training-schedule-div ontario-column ontario-small-12 ontario-large-9 ontario-margin-top-48-! ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;content&quot;]</value>
      <webElementGuid>35773e4b-df84-4786-ab6c-799c5066fd78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-add-member/div/div/div/div[2]/div/div/div[2]</value>
      <webElementGuid>fff0e6b6-3554-468b-b5f4-9839fcc6e92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member details'])[1]/following::div[1]</value>
      <webElementGuid>8864f947-80d3-4468-86d8-485b261ca5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit member'])[1]/following::div[5]</value>
      <webElementGuid>506e6188-fb9a-4f72-a153-a4c6ed3d2673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]</value>
      <webElementGuid>d19b07ec-f8ce-42a5-bdfe-eab83c2741de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'First name Last name Email addressPhone Role Designated signing authorityAdministratorAffiliate administratorInstructorAffiliate instructorOrganizationSelectAdd a new organizationAlex IT Inc' or . = 'First name Last name Email addressPhone Role Designated signing authorityAdministratorAffiliate administratorInstructorAffiliate instructorOrganizationSelectAdd a new organizationAlex IT Inc')]</value>
      <webElementGuid>9eb3c43e-7d86-47ec-b45d-cc6be80a8748</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
