<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sign in_loginfmt (1)</name>
   <tag></tag>
   <elementGuidId>e89f2c93-130f-42d3-835b-4578bc6bc5c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='i0116']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#i0116</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3651ea37-d64e-4bce-9198-876e073f7a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>92970769-8253-40c4-9a58-3ff1ee700800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginfmt</value>
      <webElementGuid>aff90586-dbe1-41d1-8f9f-8d730efeb9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>i0116</value>
      <webElementGuid>99eacee1-6175-47a8-b049-b61b813d4b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>113</value>
      <webElementGuid>6dd54bc4-a190-4a32-aa59-bf6d6a26a7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ltr_override input ext-input text-box ext-text-box</value>
      <webElementGuid>e6dc4ebc-bcd6-4dab-adbd-c86e6f3534c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f82b2b7c-0316-45fb-9f1a-a48b8b3d8870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-event</name>
      <type>Main</type>
      <value>Signin_Email_Phone_Skype</value>
      <webElementGuid>ae1cb8d0-1113-4238-92ff-097c07a45b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-trigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>954d0d6e-c85e-405f-90fe-5b2116821b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-report-value</name>
      <type>Main</type>
      <value>Email_Phone_Skype_Entry</value>
      <webElementGuid>b0a85c7e-96d6-4e0f-a9a5-7405459d8832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>
                    attr: { lang: svr.fApplyAsciiRegexOnInput ? null : 'en' },
                    externalCss: {
                        'input': true,
                        'text-box': true,
                        'has-error': usernameTextbox.error },
                    ariaLabel: tenantBranding.unsafe_userIdLabel || str['CT_PWD_STR_Username_AriaLabel'],
                    ariaDescribedBy: 'loginHeader' + (pageDescription &amp;&amp; !svr.fHideLoginDesc ? ' loginDescription usernameError' : ' usernameError'),
                    textInput: usernameTextbox.value,
                    hasFocusEx: usernameTextbox.focused,
                    placeholder: $placeholderText</value>
      <webElementGuid>d65406aa-3bd2-4364-94a5-45398f160849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter your email, phone, or Skype.</value>
      <webElementGuid>a2690011-5140-4b1c-9bbe-e5404f6a3a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>loginHeader usernameError</value>
      <webElementGuid>3ed98eee-c128-410f-9584-3f9e4b28f74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email, phone, or Skype</value>
      <webElementGuid>774c661f-3546-429e-bec1-877033c11e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i0116&quot;)</value>
      <webElementGuid>cb09eada-90bd-476f-b3c9-425c1197013f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='i0116']</value>
      <webElementGuid>25da18ce-755a-4a0c-b5ea-5cee8181c1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightbox']/div[3]/div/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>76f763d4-837e-4483-b472-a1d3876d8f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>260ae3b3-7286-496c-b48b-9e57a63157e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'loginfmt' and @id = 'i0116' and @placeholder = 'Email, phone, or Skype']</value>
      <webElementGuid>eae1c33c-65ca-453e-9cc8-b490b0ec53c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
