<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>379191bb-b11b-40df-a33f-28fad3ac6bf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='977886732-scrollable']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3676565-16d6-4f71-9624-0a510d8d7264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goog-inline-block grid4-inner-container</value>
      <webElementGuid>5d7625d7-e2b4-48db-bb3e-67b9f86ec10d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>           </value>
      <webElementGuid>707d389c-c76f-4036-ae0d-1acd03a260b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;977886732-scrollable&quot;)/div[@class=&quot;goog-inline-block grid4-inner-container&quot;]</value>
      <webElementGuid>a3dbde44-ecf2-438d-a9d0-bd43a7dc04ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>66243de0-ef03-4f1f-b6eb-53b55d944764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goog-inline-block grid4-inner-container</value>
      <webElementGuid>91477d8b-41af-44e3-8310-f465b02f12ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>           </value>
      <webElementGuid>72c84054-3c43-4f9d-93f0-433faf35fe8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;977886732-scrollable&quot;)/div[@class=&quot;goog-inline-block grid4-inner-container&quot;]</value>
      <webElementGuid>205c3152-4520-4659-a664-98b1f00bedf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='977886732-scrollable']/div[2]</value>
      <webElementGuid>3fb38e34-b780-4890-8018-cf987e329293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://intra.stage.apps.labour.gov.on.ca/public-portal-qa/#/marketplace/course-search'])[1]/following::div[261]</value>
      <webElementGuid>3d4a4421-eb0f-4775-b769-f56a68ed8f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete chart'])[1]/following::div[397]</value>
      <webElementGuid>2d4ec72d-baa4-43da-908c-01c885af96d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::div[319]</value>
      <webElementGuid>35dceb6c-f17e-4281-a039-59bc9e455047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more rows at bottom.'])[1]/preceding::div[320]</value>
      <webElementGuid>2e1be97e-e7d0-4923-9500-92f7cb7033c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]</value>
      <webElementGuid>9080754e-33f2-478d-b5dd-4820815677b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '           ' or . = '           ')]</value>
      <webElementGuid>57c52927-ec3b-4509-abe2-f97e59fb07db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 6 : Create a new test and try mobile recording (Add apk project file)'])[1]/following::div[261]</value>
      <webElementGuid>be85c83a-a067-4ee4-97ab-a0281239f590</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
