<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ (2)</name>
   <tag></tag>
   <elementGuidId>a0c73fab-4f2c-4fe5-926d-7be63678459d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='977886732-scrollable']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>328b96a3-13ac-43d6-9622-9b24b79b396d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>goog-inline-block grid4-inner-container</value>
      <webElementGuid>306bc313-727e-471d-8aa3-da704e6d35d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>           </value>
      <webElementGuid>42daed55-5d97-4631-bb34-330a86bb1b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;977886732-scrollable&quot;)/div[@class=&quot;goog-inline-block grid4-inner-container&quot;]</value>
      <webElementGuid>66e1a836-f741-4569-8562-1eef2341734f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='977886732-scrollable']/div[2]</value>
      <webElementGuid>8deef839-5617-490e-b554-3c4fa7e12041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CMs123456!'])[1]/following::div[250]</value>
      <webElementGuid>16541500-b655-41a6-b7fb-874c5f03a72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[1]/preceding::div[309]</value>
      <webElementGuid>f10935ac-4fa9-4e00-a43f-1a9d1f02a7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='more rows at the bottom'])[1]/preceding::div[310]</value>
      <webElementGuid>b416407f-7581-4aa1-9dc5-4d0d53fb2532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]</value>
      <webElementGuid>72a6a66d-ef01-40e7-8e22-38bd579c58e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '           ' or . = '           ')]</value>
      <webElementGuid>01598f32-5bb4-47e2-b346-b79e3b99eaf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
