<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tr_unread, STG No Reply My On. 5, My Ontari_44c44c</name>
   <tag></tag>
   <elementGuidId>462fdc98-03c5-4e8a-9e1a-80f9dab1ae1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id=':24']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>tr</value>
      <webElementGuid>f177e00c-7a80-4589-bd2d-19c162c73694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>zA zE aqw</value>
      <webElementGuid>eb8afcb5-f055-4144-868a-fb1b9e6200bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jscontroller</name>
      <type>Main</type>
      <value>ZdOxDb</value>
      <webElementGuid>bbc6aef3-95aa-4230-aa2e-1b064f4b69ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsaction</name>
      <type>Main</type>
      <value>Tnvr6c:RNc9jf;PG1zDd:eyrEaf;WGbBt:UL4Ddb;nVvxM:UL4Ddb;</value>
      <webElementGuid>3ab87a2a-493c-40a2-91e9-72a3ea00426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsmodel</name>
      <type>Main</type>
      <value>nXDxbd</value>
      <webElementGuid>fbbca248-dc62-4972-8cb9-6ef20aa6b447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:24</value>
      <webElementGuid>a8e6fde9-b148-453a-9840-8e7f616c1fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>31e3b665-49af-46a8-b0ab-c0e65a6d5e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>7e9da5ac-d48d-4c5c-8c33-9f2074f9202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>:25</value>
      <webElementGuid>f1226ff1-a607-478a-9ec0-0dab26df9ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8c7f9c47-136b-4767-a65d-ee000da2888c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>unread, STG No Reply [My On. 5, My Ontario Account - Action Required: One-time Verification Code, 10:53 PM, Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will.STG No Reply [My On. 5My Ontario Account - Action Required: One-time Verification Code - Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will 10:53 PM</value>
      <webElementGuid>5a2123ae-5cc6-4a64-89f8-046c52ee0be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:24&quot;)</value>
      <webElementGuid>f1155658-5ffb-4f63-8647-340029e68431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//tr[@id=':24']</value>
      <webElementGuid>df351942-6ef8-44fb-8eff-fa6abc7f6dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id=':22']/tbody/tr</value>
      <webElementGuid>1fb6a356-516e-41ca-baed-3783189b5932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='inbox settings'])[1]/following::tr[1]</value>
      <webElementGuid>00172539-1cc2-4c80-847b-1d9ce6cb0cf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Primary tab is empty.'])[1]/following::tr[1]</value>
      <webElementGuid>5a1083f4-09d2-4891-84b6-b51ab8fed348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr</value>
      <webElementGuid>6d572378-15d4-4d53-bfcc-b56201923f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//tr[@id = ':24' and (text() = 'unread, STG No Reply [My On. 5, My Ontario Account - Action Required: One-time Verification Code, 10:53 PM, Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will.STG No Reply [My On. 5My Ontario Account - Action Required: One-time Verification Code - Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will 10:53 PM' or . = 'unread, STG No Reply [My On. 5, My Ontario Account - Action Required: One-time Verification Code, 10:53 PM, Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will.STG No Reply [My On. 5My Ontario Account - Action Required: One-time Verification Code - Hi, You are receiving this email because a request was made for a one-time code that can be used for authentication. Please enter the following code for verification: 199591 The one-time code will 10:53 PM')]</value>
      <webElementGuid>32813acc-a8c8-4f05-8b8c-f996d83abdf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
