<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Assessor Portal</name>
   <tag></tag>
   <elementGuidId>46f25107-8ec0-41f0-b668-b4f3653733aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tp-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tp-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>319e7ffd-27ac-442a-abed-f939d1a51c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tp-name</value>
      <webElementGuid>b73a10d5-1011-4a9b-8fd6-405e2195411a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>473b25d5-6ae0-4392-ac5c-5826fc3e8afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Assessor Portal</value>
      <webElementGuid>d1835774-46be-4f77-bde8-daf0dcfb644b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tp-name&quot;)</value>
      <webElementGuid>80e6b0e9-6d71-4411-beae-583b51900cee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tp-name']</value>
      <webElementGuid>ca1cfe37-e92f-46c9-8455-c286671b6ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aleksey Dzhoharidze'])[1]/preceding::div[1]</value>
      <webElementGuid>e2702067-2753-454c-8946-2ea72325d632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program delivery applications'])[1]/preceding::div[4]</value>
      <webElementGuid>ef33f493-8272-4599-9a47-7027f740bcb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Assessor Portal']/parent::*</value>
      <webElementGuid>23b4b324-38a7-49f3-a87f-aadd6051f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>515e911a-cb0c-4f85-bf4c-8f0e4ed1a9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tp-name' and (text() = 'Assessor Portal' or . = 'Assessor Portal')]</value>
      <webElementGuid>adf4d0fe-7b2a-46d1-a199-0e87ed5ef00e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
