<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Applicant information</name>
   <tag></tag>
   <elementGuidId>d69c7a0e-9a97-4f36-aae4-347b6b322f94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-triage-assessment/div/div/app-triage-sidebar/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.collapsible-header.collapsed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>330c7368-4491-4d93-a4b0-5ef968500d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b86cd02-8fcf-46f8-a684-37aecc80f4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsible-header collapsed</value>
      <webElementGuid>fde367ac-0d45-415e-b33e-a7c791ee0ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Applicant information </value>
      <webElementGuid>a5abdce6-99e5-4ee1-9a15-3fd94ef8e227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-triage-assessment[1]/div[@class=&quot;ontario-row ontario-padding-top-16-! ontario-padding-bottom-40-!&quot;]/div[@class=&quot;sticky ontario-column ontario-small-12 ontario-medium-3 float-right ontario-margin-top-24-!&quot;]/app-triage-sidebar[1]/div[@class=&quot;sidebar-background&quot;]/div[@class=&quot;collapsible-header collapsed&quot;]</value>
      <webElementGuid>944bdf50-8eba-472a-84d4-990b23fdf4e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-triage-assessment/div/div/app-triage-sidebar/div/div</value>
      <webElementGuid>21a598b1-c630-4f66-a9c4-672baa56fd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAH-10289'])[1]/following::div[4]</value>
      <webElementGuid>a43551e8-bbb5-429e-9e77-cfe504776807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Working at Heights - Full'])[1]/following::div[5]</value>
      <webElementGuid>6c3eb3a8-a87d-41a6-96f8-f97fc9a0dffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attestations'])[1]/preceding::div[2]</value>
      <webElementGuid>fd6e715d-b826-4aee-8669-0604c92ca714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program documents'])[1]/preceding::div[4]</value>
      <webElementGuid>33f1bbfd-3d38-4e25-ae52-f36664c9941a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Applicant information']/parent::*</value>
      <webElementGuid>6a2e8414-129b-433d-a059-8733391817bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-triage-sidebar/div/div</value>
      <webElementGuid>386e73f8-5207-409c-975b-34ff8b497633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Applicant information ' or . = ' Applicant information ')]</value>
      <webElementGuid>1e76544b-da11-4fe6-95d3-3f5cdbaf56f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
