<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Training type All  In-person  Blended  _18fe5e</name>
   <tag></tag>
   <elementGuidId>ea7e9719-eaa2-4055-b1a1-5c30c4fde90b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main-content&quot;]/div/div/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers-search/div[1]/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ontario-column.form-input-div.ontario-small-12.ontario-medium-6.ontario-large-6.nowrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43e823e7-a8b9-474f-8eb8-911da337b184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-6 nowrap</value>
      <webElementGuid>53eae921-05ed-480b-8937-5f9bcc888c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training type All  In-person  Blended  Distance learning  Elearning </value>
      <webElementGuid>2201ccdb-057b-4145-ab72-c2b6eed78d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-safety-and-prevention-homepage[@class=&quot;ng-star-inserted&quot;]/app-tabs[@class=&quot;safety-override&quot;]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-training-providers-search[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-6 nowrap&quot;]</value>
      <webElementGuid>bc659a6e-550e-401a-a267-4e6ef8d8f762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers-search/div/div[4]</value>
      <webElementGuid>0f163c47-f6c8-4a28-8017-855b68593da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select training program'])[1]/following::div[1]</value>
      <webElementGuid>59032582-6eaf-4197-9bf1-a48b63a8107a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search approved training providers'])[1]/following::div[2]</value>
      <webElementGuid>2a3bfff8-46d6-4f22-a7f3-0ad646f245f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>2468372a-5789-488a-b478-5d475258c79e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Training type All  In-person  Blended  Distance learning  Elearning ' or . = 'Training type All  In-person  Blended  Distance learning  Elearning ')]</value>
      <webElementGuid>be90baf2-82bd-455a-bf27-0fc0c51c8fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
