<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sade_img</name>
   <tag></tag>
   <elementGuidId>4f2a9e61-9d78-4b65-98bd-48603994af03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id='img'])[94]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>27e8c34b-246c-4e2d-adaf-a02065ea0709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9dc49bc2-95e2-4dbc-9996-db3380398df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6cd88b88-e68d-4e59-921c-09acbc3a02ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style-scope yt-img-shadow</value>
      <webElementGuid>86b9942f-8d98-4fbd-90ee-95221db3d9d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>af4d986b-6520-47ed-bdd5-c8e4547b09ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://i.ytimg.com/vi/1kLIgKyYX-Q/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&amp;rs=AOn4CLBAGADDQLjrdojP0jcgOz5jZcpm6g</value>
      <webElementGuid>ffb787a9-226e-4098-8e33-26c202fdeb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondary-inner&quot;)/ytd-playlist-panel-renderer[@id=&quot;playlist&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;items&quot;]/ytd-playlist-panel-video-renderer[@id=&quot;playlist-items&quot;]/a[@id=&quot;wc-endpoint&quot;]/div[@id=&quot;container&quot;]/div[@id=&quot;thumbnail-container&quot;]/ytd-thumbnail[@class=&quot;style-scope ytd-playlist-panel-video-renderer&quot;]/a[@id=&quot;thumbnail&quot;]/yt-img-shadow[@class=&quot;style-scope ytd-thumbnail no-transition&quot;]/img[@id=&quot;img&quot;]</value>
      <webElementGuid>f44a6d64-ca36-4164-b162-21d3cdbef959</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id='img'])[94]</value>
      <webElementGuid>d38d9f50-386b-488d-843a-5c6633c9cd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='thumbnail']/yt-img-shadow/img)[54]</value>
      <webElementGuid>928ad641-0fb3-4124-8a87-95d39c348587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://i.ytimg.com/vi/1kLIgKyYX-Q/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&amp;rs=AOn4CLBAGADDQLjrdojP0jcgOz5jZcpm6g')]</value>
      <webElementGuid>72497d74-059e-49b1-a73d-ad6ff7a37333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-playlist-panel-video-renderer[21]/a/div/div[2]/ytd-thumbnail/a/yt-img-shadow/img</value>
      <webElementGuid>d6ca1bbb-0f95-4437-90de-83b1ba687062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img' and @src = 'https://i.ytimg.com/vi/1kLIgKyYX-Q/hqdefault.jpg?sqp=-oaymwEbCKgBEF5IVfKriqkDDggBFQAAiEIYAXABwAEG&amp;rs=AOn4CLBAGADDQLjrdojP0jcgOz5jZcpm6g']</value>
      <webElementGuid>1d9dd5f6-954f-47b7-9da5-457f34bd8263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
