<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Training Program All programsJHSC - Par_b4b9a9</name>
   <tag></tag>
   <elementGuidId>67fb2313-df7b-4d09-85a7-112c9d631ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ontario-column.form-input-div.ontario-small-12.ontario-medium-6.ontario-large-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-schedules/div/div/div[2]/app-training-schedule-search/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07dedd1b-18cd-4d80-acbe-d79061b21d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-3</value>
      <webElementGuid>ca0ba961-0e6c-4256-8cfc-fcc58e4c16c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training Program All programsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights</value>
      <webElementGuid>5c7d3512-0b4c-42a5-845c-64c22a7a0e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-schedules[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-margin-top-16-!&quot;]/app-training-schedule-search[1]/div[@class=&quot;search-criteria-container ontario-padding-right-24-! ontario-padding-left-24-!&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-3&quot;]</value>
      <webElementGuid>658772ab-92b0-4d33-859d-bea5b9e84799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-schedules/div/div/div[2]/app-training-schedule-search/div/div/div</value>
      <webElementGuid>2d886afd-d854-4e55-9f2b-0fe226b257b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a classroom'])[1]/following::div[4]</value>
      <webElementGuid>9c0a3207-2ee4-4be1-a874-dcdafa292886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My training schedules'])[1]/following::div[4]</value>
      <webElementGuid>742cb930-479d-4280-847b-d30db4fce468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instructor/evaluator'])[1]/preceding::div[1]</value>
      <webElementGuid>2f0a4a7c-2e05-4f60-9a93-ace7014d8e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-training-schedule-search/div/div/div</value>
      <webElementGuid>4a381691-3090-4440-bd35-05fc11f4ea40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Training Program All programsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights' or . = 'Training Program All programsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights')]</value>
      <webElementGuid>e103a49e-adeb-41fe-8508-d022e906b744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
