<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Show listings with course fee onlyWeeke_3648a5</name>
   <tag></tag>
   <elementGuidId>f4770610-c134-4e0e-a4d4-41519a5e3957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.inline-container.ontario-column.form-input-div.ontario-small-12.ontario-medium-6.ontario-large-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-training-schedules/div/div/div[2]/app-training-schedule-search/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63c71f9c-02fe-45f1-a0d6-8672cf613179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-container ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-6</value>
      <webElementGuid>2d8eaaef-7d3f-4b19-a412-34dd50575ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Show listings with course fee onlyWeekend classes only</value>
      <webElementGuid>256d649e-21d8-42f4-8b4a-1ebee709fe9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-training-schedules[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-margin-top-16-!&quot;]/app-training-schedule-search[1]/div[@class=&quot;search-criteria-container ontario-padding-right-24-! ontario-padding-left-24-!&quot;]/div[@class=&quot;ontario-row ontario-margin-top-24-!&quot;]/div[@class=&quot;inline-container ontario-column form-input-div ontario-small-12 ontario-medium-6 ontario-large-6&quot;]</value>
      <webElementGuid>16cc7b31-717b-425f-a318-07bd49f82807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-training-schedules/div/div/div[2]/app-training-schedule-search/div/div[3]/div</value>
      <webElementGuid>44150b8b-ee1e-4cee-ae39-25476b1c2aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='French'])[1]/following::div[2]</value>
      <webElementGuid>d96be3a7-d96a-43df-8da8-e8fbab5ec3d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[2]</value>
      <webElementGuid>1f13ed24-7867-4341-9d82-64b70b7e5694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>ca9a06e0-c1fa-4890-a5fd-09d9cd494412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Show listings with course fee onlyWeekend classes only' or . = 'Show listings with course fee onlyWeekend classes only')]</value>
      <webElementGuid>de8900e9-4b5a-457c-bb68-a24ea98d96cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
