<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First name  Last name  Email  Phone num_9af684</name>
   <tag></tag>
   <elementGuidId>ae5446f6-a076-4e3c-b93b-99d4e29816ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-my-team/div/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.table-row.table-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9d940b2-5eea-448c-bbc9-7a57527d0e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table-row table-header</value>
      <webElementGuid>5ab596f4-a7fb-41df-9027-03c0dc438a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> First name  Last name  Email  Phone number  Role(s)  Organization  Location  Last login </value>
      <webElementGuid>51ccca67-07b6-4b6c-a46b-3342841fb53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-my-team[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-margin-bottom-48-!&quot;]/div[@class=&quot;teams-table&quot;]/div[@class=&quot;table-row table-header&quot;]</value>
      <webElementGuid>e6585223-023b-4b56-a44a-50d0cab90b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-my-team/div/div/div[3]/div/div</value>
      <webElementGuid>3635a21a-3257-44d1-b6c1-ba73f9e2cd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/following::div[3]</value>
      <webElementGuid>21459b3d-3d7d-45b9-ab74-631db246a3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[4]</value>
      <webElementGuid>8d840d25-c8c0-4991-a235-3981812d1d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>b3337f71-22a3-4500-b9a7-6ac0c9f63fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' First name  Last name  Email  Phone number  Role(s)  Organization  Location  Last login ' or . = ' First name  Last name  Email  Phone number  Role(s)  Organization  Location  Last login ')]</value>
      <webElementGuid>762e3fbb-b91e-44ad-8c28-7f314f04be31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
