<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Start new application (2)</name>
   <tag></tag>
   <elementGuidId>0261398a-ae26-4551-9054-7b694a9560ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#start-new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='start-new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65b003ee-8cad-414b-b7a4-0cf2c962b8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>start-new</value>
      <webElementGuid>77db1e36-7808-4006-9066-dfc6f93d6b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue-button</value>
      <webElementGuid>369a384a-2feb-4a18-b7b9-40511ccdfa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Start new application </value>
      <webElementGuid>683a16ef-32dc-4dd3-9ea5-e08f18520796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;start-new&quot;)</value>
      <webElementGuid>ddf7e2d3-5e65-4e6f-a6f5-f3d46a851518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='start-new']</value>
      <webElementGuid>ecca6278-a99b-40f2-a2b1-16d897c714c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div[3]/div/div/div/button[2]</value>
      <webElementGuid>cec2db9e-b664-4c5e-8fd1-b453ccfe1575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>1d79ec2b-bfb2-46c2-b63a-fa87034e0e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety Training Formats'])[2]/following::button[2]</value>
      <webElementGuid>855d4e58-66b0-412d-bf04-8dcc88b17961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ministry of Labour, Immigration, Training and Skills Development'])[1]/preceding::button[4]</value>
      <webElementGuid>20fa0630-8efc-426a-ae95-8406feb5a60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Ontario'])[1]/preceding::button[4]</value>
      <webElementGuid>0c3616fe-05f3-44c5-a6c1-b50e84541196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Start new application']/parent::*</value>
      <webElementGuid>fbf81a76-54f1-4563-89e4-7cd6a66115eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>c2fb7f24-a6a9-4a1b-8712-438fc4e6b6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'start-new' and (text() = ' Start new application ' or . = ' Start new application ')]</value>
      <webElementGuid>62dbdd8e-1030-4ac1-8476-b58bb189f1a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
