<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Application for new training program delivery</name>
   <tag></tag>
   <elementGuidId>662bf85a-1042-4592-a784-be3595571c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.border-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>23991410-a2fb-4e8d-affe-b1907d8788a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-bottom</value>
      <webElementGuid>2ed52520-f2f2-4378-9ae1-abafdc0fe77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Application for new training program delivery</value>
      <webElementGuid>4f9e1743-e081-4127-b4ca-8a2841c67ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/h2[@class=&quot;border-bottom&quot;]</value>
      <webElementGuid>7f2d815f-11f1-4a83-9e5d-e0c8512e6624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>467fdf78-6d6a-4dd8-bf05-6587dded1447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-bottom</value>
      <webElementGuid>02fd7d68-3877-4c3b-ac19-cbf5bc507413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Application for new training program delivery</value>
      <webElementGuid>6603c029-8346-4b40-be98-a4864efc9442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/h2[@class=&quot;border-bottom&quot;]</value>
      <webElementGuid>a2059edb-a29f-486d-b6bc-67218fcd2ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/h2</value>
      <webElementGuid>d691f2a9-b7a4-4dc3-94bd-569969b7a4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Johathan Doe'])[1]/following::h2[1]</value>
      <webElementGuid>56707595-4765-4eda-b9e5-dfd0771672de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABC Training Inc.'])[1]/following::h2[1]</value>
      <webElementGuid>31eeb9de-e390-4938-9cdb-51f86ff4b246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please use the following sections to tell us about your training program.'])[1]/preceding::h2[1]</value>
      <webElementGuid>4d610f5c-ef6a-4243-8e08-20715c685a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select training program'])[1]/preceding::h2[1]</value>
      <webElementGuid>77227d76-f4e2-4ab7-90d8-6fe733149b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Application for new training program delivery']/parent::*</value>
      <webElementGuid>d24fd6c3-989e-4c86-b4a5-92e1f8074178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2757617f-b76b-40ab-8b7d-afefe7c225e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Application for new training program delivery' or . = 'Application for new training program delivery')]</value>
      <webElementGuid>3ebf5e93-3b64-43ce-a196-9b32cb752522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
