<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Blended_radio-buttons-0.4743901969608175-3</name>
   <tag></tag>
   <elementGuidId>a2f720b4-e9f2-41a0-a716-ddbba4ba269e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.4743901969608175-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dccf2d9-8dc4-41de-aff0-3847b5170c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>88ebd41d-43c5-4064-b060-bc8b62e160c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>31430e0a-4fbe-447c-9182-ce91c25e85f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.4743901969608175-3</value>
      <webElementGuid>2ec6f24e-cdd0-498b-96b6-b6431ae9e09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.4743901969608175-3</value>
      <webElementGuid>45bb5c50-e716-4e17-9f13-cbd677d51681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>c5d83005-e948-469e-8695-bf656dd613bf</value>
      <webElementGuid>50de9d7c-d594-4718-81b1-e10c8c040915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.4743901969608175-3&quot;)</value>
      <webElementGuid>bc15234e-011f-4edb-8a34-ce6552150c16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.4743901969608175-3']</value>
      <webElementGuid>feb0fd78-26cb-4bbc-aff4-af52ba1f77f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[6]/input</value>
      <webElementGuid>e6bf161d-c3b3-4b15-995b-7ab7e8180d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>dab25178-9547-4a57-a9fc-6f54febc6ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.4743901969608175-3' and @name = 'radio-buttons-0.4743901969608175-3']</value>
      <webElementGuid>e603ba8e-8a2a-4266-8ae8-fb67802b52af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
