<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You have to submit a separate applica_178d41</name>
   <tag></tag>
   <elementGuidId>5056c7c9-123e-4ba0-b035-2b0271ee459c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.3396058897528842-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9d361d4-ecc0-4509-8f2d-884558da6470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>881f32e0-9977-469a-b45d-d09d0ee2eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>1db29532-9d26-4295-b4d6-a458904519d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.3396058897528842-0</value>
      <webElementGuid>0ead06cf-c861-4675-aec1-fdd4616f5adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.3396058897528842-0</value>
      <webElementGuid>971fa5e7-fd25-4a48-86c9-b09691d03e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>e15c8a24-14b5-4fc6-9ea4-9f1a95d5f810</value>
      <webElementGuid>f55e5b6f-7dc6-4c80-9f6e-a5b8e45a04ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.3396058897528842-0&quot;)</value>
      <webElementGuid>1d9c2644-3ffd-4a99-8c04-ac72cea01e39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.3396058897528842-0']</value>
      <webElementGuid>1c5eb18c-9c63-4ebc-b5e9-205ab1a1c2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[3]/input</value>
      <webElementGuid>2fa3519a-094b-4d1d-91c6-88633f23fdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/app-radio-button-list/div[3]/input</value>
      <webElementGuid>a1833b9d-980a-4c34-ab0c-6430be2eb734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.3396058897528842-0' and @name = 'radio-buttons-0.3396058897528842-0']</value>
      <webElementGuid>48ea12b3-214a-46cb-8937-48ce12dd7ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
