<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Blended_radio-buttons-0.5562938137709188-3</name>
   <tag></tag>
   <elementGuidId>683f40d3-264a-4bf6-9f1b-91c93b6db5bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.5562938137709188-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d4da8bb-be55-4fd0-8ad1-689223f4a5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>38ba2442-f52f-498d-b30a-3b367c6c96c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>798cb452-1146-401e-97b7-b34f228dfcd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.5562938137709188-3</value>
      <webElementGuid>7b36d795-a077-4e8b-b0da-0e8e19fc8b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.5562938137709188-3</value>
      <webElementGuid>4db04e72-7d7f-44b3-8756-8a9277de4b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>c5d83005-e948-469e-8695-bf656dd613bf</value>
      <webElementGuid>4ceb9e53-5d19-4bf2-83b0-1cf564dac5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.5562938137709188-3&quot;)</value>
      <webElementGuid>695e522a-f521-4d4e-93cf-9179953c524e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.5562938137709188-3']</value>
      <webElementGuid>591f666a-9796-469a-912f-64da951d7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[6]/input</value>
      <webElementGuid>23a64bc7-3c00-47b8-8670-e48e03a3b73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>fa1fec3d-6a0d-4a9f-ac01-8a610ab7f067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.5562938137709188-3' and @name = 'radio-buttons-0.5562938137709188-3']</value>
      <webElementGuid>02982ea4-51e4-4524-b63f-accb272ac3ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
