<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You have to submit a separate applica_80fdc1</name>
   <tag></tag>
   <elementGuidId>04014e75-2501-4600-9ecf-602423e3b361</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.2692673357021469-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>170a4cb4-8267-49b1-adba-3b190d359c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>31b8d2e1-d557-42c2-b474-99f3c2b5564a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>131f1047-89c9-41e3-b5bc-d472b26e9967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.2692673357021469-0</value>
      <webElementGuid>b2dc0286-0ac5-48f4-ac2e-4f0f2a878b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.2692673357021469-0</value>
      <webElementGuid>8db65721-8b1d-4704-97ce-2a7617e9c4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>e15c8a24-14b5-4fc6-9ea4-9f1a95d5f810</value>
      <webElementGuid>e1e7ec5a-9428-4e9d-90c8-913be25217e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.2692673357021469-0&quot;)</value>
      <webElementGuid>57279036-8923-4c4c-baf0-420aa955e56b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.2692673357021469-0']</value>
      <webElementGuid>3965d771-67ce-4f4b-af73-d84a00cd802f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[3]/input</value>
      <webElementGuid>be7d69c4-aee4-40b5-8fa8-d2e59b1ac4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/app-radio-button-list/div[3]/input</value>
      <webElementGuid>7560ed8e-1373-4b0d-a5a4-2b434192e588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.2692673357021469-0' and @name = 'radio-buttons-0.2692673357021469-0']</value>
      <webElementGuid>d63c3303-59c5-416d-9aa2-d8e1ac4a1965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
