<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_You have to submit a separate applica_d4434d</name>
   <tag></tag>
   <elementGuidId>e20eba8d-5df1-46a0-a671-24e7919a21bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.4487741934992151-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35d29058-e6ee-4bf4-93d3-b76fca95202d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a4af6c61-b155-4be0-9b56-e8c421eb6bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>5217271d-4d37-4fce-a545-b0b439efec55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.4487741934992151-0</value>
      <webElementGuid>597d52bd-c4b9-429f-8ea7-ee6be8f60cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.4487741934992151-0</value>
      <webElementGuid>07bd5243-605d-481b-85b0-93c1c9a7ae98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>653d79d5-1ebf-4edf-83ab-5e71ed2d4307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.4487741934992151-0&quot;)</value>
      <webElementGuid>0a0b7d46-e00d-4b4c-a25f-40ba3396b298</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.4487741934992151-0']</value>
      <webElementGuid>1e303f39-2522-4605-bc5f-a97c29c1c6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[3]/div/app-radio-button-list/div[3]/input</value>
      <webElementGuid>782ad263-68ca-4dfc-8648-5fedb8d6808d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>09c2d43b-27c5-48c8-8674-06c2fc590413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.4487741934992151-0' and @name = 'radio-buttons-0.4487741934992151-0']</value>
      <webElementGuid>1ec80907-bdd2-45ee-ab5b-c7d804096096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
