<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Blended</name>
   <tag></tag>
   <elementGuidId>0ec0b16a-02c7-49d5-a224-5d9196a95342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b3a23c03-0d85-4448-b9b1-365db1b6f942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>c6a36167-719f-4ccf-8fa2-7e810c9c51af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.15494244286328018-0</value>
      <webElementGuid>a29a3962-3637-4802-a1a7-7c52aa0e2741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>9fad3087-c14d-4cdf-bf7e-7aaab707ce56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>440965f0-af6a-4407-8a01-1ec718263eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e55a2d86-068c-4d45-915d-05c2ee8a3b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>1198a28c-8ff1-4c0b-a5f2-74561445c015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.08775340405638343-0</value>
      <webElementGuid>1d583195-e87c-469f-badb-5b7b6977da0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>afc90e1c-444b-4f96-9e2b-b9583a07954a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>d168354e-8266-4712-b324-e711129c072c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8e2f9c60-4884-4f95-965b-852053ed735a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>1b4ce7bf-179a-4a95-ba39-f2e2ba100d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.92150042393547-0</value>
      <webElementGuid>6cb12510-a80a-4a54-8167-18b9afaf373b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>069d7ba5-9ebc-4ef9-ba54-a253a4f3da4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>f4a87689-8f68-4be3-9435-92b70f4a4ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9de45d5e-6c01-4849-afc2-afd4974ccc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>bf94a043-9efe-4190-a7c5-8b4f5cd3cfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>2b634264-d053-4abc-b7e5-d1caf999021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>7311390b-c233-4ce0-8fd5-61f653c603f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>0faf94ed-c821-45e0-b811-b4ff8c46f2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>afda8136-857e-4ee7-a6c8-6c9b76147fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>b3dfe52e-f1aa-410e-b3f1-d72dbd240f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>d4b27b67-fad3-4097-8366-2acd97409b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>dd57606f-100c-4c7a-9c65-a70cb50f6961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>cc7c195a-bae2-4967-bf6a-ff7323e87e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5482071c-4031-4ca8-9fd1-782b9bd351f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>1013384a-a463-4791-809b-5fe2c374ea39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>81407220-80d2-417e-b4ef-6ad3a4a6294f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>0e1bc3d8-572b-4912-be68-eaaf76ba5414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>1e88b95c-636e-4b83-9d25-a6e61acc1e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>51414f64-a493-4713-899a-b912341a12df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>13ea849b-e7e6-44f2-8691-d18bcd22c01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>04cfa875-afb5-47c4-bc14-a3dfb5f0ccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>ea67662c-e7f9-4c35-b38d-0b426db60382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>eb76f59a-d7db-4338-bd62-e5c0d8d8e304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>254cc9c2-a218-490e-872d-60051cb9ccb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>06e4ef3b-0af5-4c67-8b1c-551efe0df3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>e3cee8b4-4cf8-47b9-9973-0dc9789ca46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>cf3fb3e3-40fc-4cd9-b187-b89eb9b52ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>d5e1ab27-2c72-4bd2-962b-a360f43722ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>08e83fad-369f-4083-9f9f-4cf8ec5a2733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>0c43ec9e-9c16-4933-b7a0-be088bdb9729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>322fb1db-3a24-407e-ad46-ffb736f7fc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>7f5d5e62-36ae-4277-8901-8a0419acac76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>04b922e9-261a-4759-b89a-9fa564623950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>300e2a18-7cb6-48a3-8124-b3646aec9e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>d6218721-2c3c-4511-bdeb-2d9d283a3a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>d1c46d4e-a4fc-4a09-8d10-d140031bcd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>60390f1e-68ee-469b-85a1-742a9d82fc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>ae31150d-f477-438f-a887-295d13cfb5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>120f36e9-075d-4f27-b3e2-c39501b5132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>75845259-d13f-4b4e-8e8d-0b8104a81ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>d04717ce-1079-4a0b-a633-a90907eb9e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>ccca4373-3c1b-4889-92d8-36e56dda89d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>76a813ef-4cb5-4c56-a3b9-3b91b7b34b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>da104dc8-8962-43fa-8fa6-5cc03998db34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>08559b65-9aab-4cc7-99b1-86606ad80614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>12c59401-8c93-4399-b54e-dd3f3f0f5f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>9026b666-f765-4521-b94f-a87df97b22b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>1eeff41e-5532-4616-bdb0-52bda42f74f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9f0ec6b8-d8ef-49de-b4ce-97877512fa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>aac2d44f-b7b2-477e-b24b-744089f67e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>a9c2bebc-301e-4244-b3d1-0afffa26c779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>c8f3b348-611e-423c-9502-2093409301a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>94ecbc41-9ea4-428f-9078-ddcebaa19381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9699392f-41be-4623-9eae-7f65580ec978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>bc23df8a-1185-4863-8201-2f00f17ac3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>f1232357-df5f-44da-bf19-70f78aa68f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>aa9bfe93-8bcf-4d07-8ef5-efdf73bf8a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>56a0cd01-da3d-4ad7-b345-810ea8f9962d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9f268b52-8ab2-4efa-ae29-d6b594456a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>0b4caca0-e8ba-464f-b15a-dc7601f82539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>767fd058-5e75-4d12-92d7-ff3f8a7b2c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>ddedd8cf-1e23-4415-8887-1245f57de422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>77acab05-e0d9-428e-8ec4-90b12feff360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5c047e98-6d65-4cd0-a04d-756122a575ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>98e733e4-9736-447c-b19d-1683c7ad0c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>24871e27-2a70-496e-9fd7-3f7645f54484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>67810b7b-fcab-413f-9c06-e2fe5764bc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>fe3865bd-0676-40b9-8e8d-1f2e20e6fec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d0b9bcab-529e-46b2-a8ec-411ddd807fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>179b110d-ea98-44c7-b7ea-04f227290ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>5c02a7ca-48d8-440e-9396-611a83422695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>8760fe15-832b-466b-9b50-81c03f2a07e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>3b974c7f-a07f-47fe-b1be-e60cb64c53e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>796b5683-fb09-4caf-95a8-078305d4306a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>f7aa1347-c7e4-4862-b167-89c2eaff0873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>8b1b9fef-ff02-466c-aeae-e840b58d5155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>5329154e-51c2-45cb-a596-9bc246ad360a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>faf626d4-0cc2-4180-9f03-7b153f349360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>77c4a9ed-9b3f-487a-a77e-ccd46d14331f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>41107a8c-2dcb-4402-ba3a-53acd87f0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>1559cee2-9973-4213-894c-0ab1c268541c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>ed7993e6-e0b3-4e61-ad9f-06834a3e39df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>f7fa64d2-a7bb-42ae-abaa-92d27f13b64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>df464726-8fc6-4b1b-9365-d8b1d66aab62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>153a974b-367e-4e98-90ac-dc2fdec5a276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>c3472139-423d-47b1-af65-6e223f41d062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>d5bb48eb-e9c5-4284-a381-3b7d162824c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>ef1b620a-088f-4fed-bd32-36308eaa5b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9c53860d-0d49-49b7-8fef-2d9232c112b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>fdda9f2d-2296-4b5d-b81f-3d643d880742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>fd909731-cf23-477f-99b5-4dda3f8e7c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>21f3c745-84be-41d9-ad76-93da626059b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>c2aa343e-5be5-440c-86ab-3afb0f68f15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>967f5e33-4ea2-4968-bc0c-b15268d309a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>ed9de246-4ce8-467c-8ac8-b5b0ca795399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>81206a34-8dcf-4708-8ce2-ee8e97904cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>e89c1d28-e266-4a8a-b202-e5011270e163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>9737752f-2c5a-4164-a277-a20e43efcb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>13dbf8ae-8f99-429a-91c3-9ebcb2075aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>d71c4ce3-9626-4892-8c2b-2017909de950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>b872b21c-9c0e-431c-ada3-c775cca6a37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>24ca6734-643f-468b-af0d-ea1f19c86335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>6f3fe494-753c-422e-934f-00a991c17f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>54ca92ab-4af9-48f4-bbd4-7581e020b415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>8e07e98a-a61b-4cbe-80d4-03c8ef1d3368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>078c025d-996a-42e1-b3b1-b8b95733b3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>4445d8ec-e00b-4344-9766-00b5b81892cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>7e497d39-128e-4579-8290-482f2a2edbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5326d449-f42d-4b34-9610-7816f07eb0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>aae70357-aed8-47d4-b981-3c8aefec0239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.8633308338648373-0</value>
      <webElementGuid>e72df092-05de-4e6a-9fbc-52048fb92cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>d5bf42db-7ec9-4e12-9248-aa39ad979a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>1eca8b6a-6576-488c-b899-d573c7f680da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>141cd9f1-f8c2-4b3d-8670-3a833729efc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>f41c847b-8bd6-4335-8370-2fa002a32e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.3079296737541932-0</value>
      <webElementGuid>bd59c452-af92-4397-ad80-f5e3e92aff7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>78e6c221-396d-459a-bf3c-cbdece123b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>c98ec41b-046a-42dd-81d4-9402942e7ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>14f81298-758f-4107-9e94-839116470822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-label ontario-radios__label</value>
      <webElementGuid>3b5023d1-eb92-4e47-a186-3ece36d887de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>radio-button-option-0.9213357034839205-0</value>
      <webElementGuid>883bab22-8902-4553-9634-269e04cb4918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Blended </value>
      <webElementGuid>206fffaf-8dfb-487c-b574-8259a3c49fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-application-for-new-training-delivery[1]/div[@class=&quot;ontario-row ontario-margin-top-16-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-9&quot;]/div[@class=&quot;ontario-row ontario-padding-left-0-! ontario-padding-top-8-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-8&quot;]/app-radio-button-list[1]/div[@class=&quot;ontario-radios__item&quot;]/label[@class=&quot;ontario-label ontario-radios__label&quot;]</value>
      <webElementGuid>f97c5a43-a6b8-4bad-9c2a-df3800b8cf97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-application-for-new-training-delivery/div/div/div[4]/div/app-radio-button-list/div[3]/label</value>
      <webElementGuid>4e351c48-b399-4d8b-ab42-02fdb7e9a768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have to submit a separate application for each training format.'])[1]/following::label[1]</value>
      <webElementGuid>062d703b-ddec-46e1-abcb-838752cd5cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the training format that you want to deliver the training in?'])[1]/following::label[1]</value>
      <webElementGuid>9b3cb5e3-3936-4778-a98f-b413b44faaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Class'])[1]/preceding::label[1]</value>
      <webElementGuid>0d60ded0-4e9d-4baa-bef1-6d05bc338e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blended']/parent::*</value>
      <webElementGuid>584651aa-f891-40df-a311-393d86446e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/app-radio-button-list/div[3]/label</value>
      <webElementGuid>d7ea71ff-3f19-4f35-bfed-a9b8a164980d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Blended ' or . = ' Blended ')]</value>
      <webElementGuid>f69212a8-e530-4a0d-9925-5dc49ea3f2fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
