<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Training delivery modes for Working at _1556d0</name>
   <tag></tag>
   <elementGuidId>02d25b7b-fb4b-4879-b5d8-8028c3a6457f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.paragraph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div/app-page-content-loop/app-grey-text-box-sidebar[2]/div/div[2]/div[2]/app-page-content-loop/app-dynamic-tab-list/app-page-content-loop/app-generic-paragraph/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b8b3a04-b0eb-4ee3-b989-dd8003e8f8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>paragraph</value>
      <webElementGuid>2a96ecae-b727-4774-988d-24f456895918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training delivery modes for Working at HeightsFace-to-face (in-class) trainingRefers to traditional classroom training, in which an instructor teaches a course to a room of training participants.Blended learningDescribes the practice of using several training delivery methods in one curriculum. It typically refers to the combination of classroom instruction and any type of training that includes self-directed use of online capabilities.</value>
      <webElementGuid>2d4e09c3-76f5-4789-8698-802a8af111ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-safety-and-prevention-homepage[@class=&quot;ng-star-inserted&quot;]/app-tabs[@class=&quot;safety-override&quot;]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-training-providers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-3 float-right&quot;]/app-page-content-loop[1]/app-grey-text-box-sidebar[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]/div[@class=&quot;sub-section ng-star-inserted&quot;]/app-page-content-loop[1]/app-dynamic-tab-list[@class=&quot;ng-star-inserted&quot;]/app-page-content-loop[@class=&quot;ng-star-inserted&quot;]/app-generic-paragraph[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;paragraph&quot;]</value>
      <webElementGuid>30ffe4be-c8f6-46d8-9f7f-83f5c31db8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div/app-page-content-loop/app-grey-text-box-sidebar[2]/div/div[2]/div[2]/app-page-content-loop/app-dynamic-tab-list/app-page-content-loop/app-generic-paragraph/div</value>
      <webElementGuid>ad48f65f-4386-4c30-af33-8cd404e15981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JHSC'])[1]/following::div[2]</value>
      <webElementGuid>725bf8f1-89c5-453f-88d4-84619d285587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAH'])[1]/following::div[3]</value>
      <webElementGuid>4c090105-8ac6-4a90-81e4-5c841cffe531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-generic-paragraph/div</value>
      <webElementGuid>3bf129e9-20ff-423f-870c-af5495ebed7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Training delivery modes for Working at HeightsFace-to-face (in-class) trainingRefers to traditional classroom training, in which an instructor teaches a course to a room of training participants.Blended learningDescribes the practice of using several training delivery methods in one curriculum. It typically refers to the combination of classroom instruction and any type of training that includes self-directed use of online capabilities.' or . = 'Training delivery modes for Working at HeightsFace-to-face (in-class) trainingRefers to traditional classroom training, in which an instructor teaches a course to a room of training participants.Blended learningDescribes the practice of using several training delivery methods in one curriculum. It typically refers to the combination of classroom instruction and any type of training that includes self-directed use of online capabilities.')]</value>
      <webElementGuid>0acca5e3-c1c1-4364-951b-b9c0665fe2a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
