<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Working at height training WAHThis Work_995ab9</name>
   <tag></tag>
   <elementGuidId>92d951cd-baf6-441a-a61e-5a11f5772ea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-grey-text-tile.ng-star-inserted > div.grey-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div[2]/app-page-content-loop/app-grey-text-tile/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>122ec2bd-ea4c-4b8c-acbd-4b07c36cd687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey-box</value>
      <webElementGuid>14077c3e-ce41-42fb-8b89-b37e0b78b1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Working at height training [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer (CPO) for approval. It should be read in conjunction with the Working at Heights Training Provider Standard, which sets out the requirements that must be met by training providers seeking approval by the CPO to deliver an approved working at heights training program. Read provider standards Read program standards</value>
      <webElementGuid>655cc8b2-20e2-4b40-96e7-d72d379ce314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-safety-and-prevention-homepage[@class=&quot;ng-star-inserted&quot;]/app-tabs[@class=&quot;safety-override&quot;]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-training-providers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9&quot;]/app-page-content-loop[1]/app-grey-text-tile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grey-box&quot;]</value>
      <webElementGuid>b38a5015-17cc-4078-8c1f-9c1a89f74f21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div[2]/app-page-content-loop/app-grey-text-tile/div</value>
      <webElementGuid>2c322c61-9fce-4b19-82ee-f4dd6ff07b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CPO-approved training programs'])[1]/following::div[1]</value>
      <webElementGuid>4786ff2d-8ba1-465e-a196-e507562ac78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register as training provider'])[1]/following::div[1]</value>
      <webElementGuid>80a44eee-8156-4dec-94bf-403ed328eb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-grey-text-tile/div</value>
      <webElementGuid>524ced14-e94a-4f59-a267-07f3980d9789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Working at height training [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer (CPO) for approval. It should be read in conjunction with the Working at Heights Training Provider Standard, which sets out the requirements that must be met by training providers seeking approval by the CPO to deliver an approved working at heights training program. Read provider standards Read program standards' or . = 'Working at height training [WAH]This Working at Heights Training Program Standard sets out the requirements that must be met by training programs submitted to the Chief Prevention Officer (CPO) for approval. It should be read in conjunction with the Working at Heights Training Provider Standard, which sets out the requirements that must be met by training providers seeking approval by the CPO to deliver an approved working at heights training program. Read provider standards Read program standards')]</value>
      <webElementGuid>d0fb9af9-9d3c-4348-883d-aba9d938b582</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
