<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Joint health and safety committee train_17599b</name>
   <tag></tag>
   <elementGuidId>ff2425fd-df22-4884-93c2-0594fd19b9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div[2]/app-page-content-loop/app-grey-text-tile[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46a072ec-a523-498e-8e76-c3ef24bc4070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grey-box</value>
      <webElementGuid>d6c60881-8373-4e03-92ca-addeca84e572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Joint health and safety committee training [JHSC]: Part 2Certification of certain Joint Health and Safety Committee (JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act (OHSA). The JHSC Certification Training Program Standard specifies the criteria that a program must meet in order to be approved by the Chief Prevention Officer (CPO). Read provider standards Read program standards</value>
      <webElementGuid>c07c4983-060f-4ffc-b3e7-cfde43172726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-safety-and-prevention-homepage[@class=&quot;ng-star-inserted&quot;]/app-tabs[@class=&quot;safety-override&quot;]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-training-providers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-9&quot;]/app-page-content-loop[1]/app-grey-text-tile[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grey-box&quot;]</value>
      <webElementGuid>43930f8b-b871-49de-b623-79664f107def</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-training-providers/div/div[2]/app-page-content-loop/app-grey-text-tile[3]/div</value>
      <webElementGuid>d0de83de-48f7-42b4-b035-dd35ccc63f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read program standards'])[2]/following::div[1]</value>
      <webElementGuid>883c5cc5-c8c7-4447-81d8-b015b4893d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read provider standards'])[2]/following::div[1]</value>
      <webElementGuid>4d14df6e-5904-4f4a-b6d3-4c38333bbe79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-grey-text-tile[3]/div</value>
      <webElementGuid>1419e6bf-03d1-4365-b4af-15eed13c653c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Joint health and safety committee training [JHSC]: Part 2Certification of certain Joint Health and Safety Committee (JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act (OHSA). The JHSC Certification Training Program Standard specifies the criteria that a program must meet in order to be approved by the Chief Prevention Officer (CPO). Read provider standards Read program standards' or . = 'Joint health and safety committee training [JHSC]: Part 2Certification of certain Joint Health and Safety Committee (JHSC) members is required under section 9 of Ontario’s Occupational Health and Safety Act (OHSA). The JHSC Certification Training Program Standard specifies the criteria that a program must meet in order to be approved by the Chief Prevention Officer (CPO). Read provider standards Read program standards')]</value>
      <webElementGuid>f012439e-a0f1-4651-8164-4fa607b435fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
