<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_9.2.2Personal fall protection equipment</name>
   <tag></tag>
   <elementGuidId>e2e0e2fb-e5a9-4384-8ef4-fcc41ec63171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-tab[@id='reqs-tab']/div/div/app-requirements-section-list/app-requirements-input[9]/div/div/app-accordion/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0aecb831-e54a-4fd6-a39c-7f404fee38fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-row</value>
      <webElementGuid>70b67d3c-1323-4641-a7cd-2440c1c23a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9.2.2Personal fall protection equipment</value>
      <webElementGuid>633a7904-9ee0-4920-8706-2a325acc9fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reqs-tab&quot;)/div[@class=&quot;tab&quot;]/div[@class=&quot;ontario-row margin-left-0px&quot;]/app-requirements-section-list[1]/app-requirements-input[9]/div[@class=&quot;ontario-column ontario-small-12 ontario-medium-11 float-norm&quot;]/div[@class=&quot;accordion-div&quot;]/app-accordion[1]/div[@class=&quot;accordion-heading&quot;]/div[@class=&quot;accordion-row&quot;]</value>
      <webElementGuid>cde78ad6-f122-4964-9d76-d949c916a30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-tab[@id='reqs-tab']/div/div/app-requirements-section-list/app-requirements-input[9]/div/div/app-accordion/div/div</value>
      <webElementGuid>f6d6823e-2e73-47ef-9e1a-54bb86f41081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barriers and other fixed equipment'])[1]/following::div[5]</value>
      <webElementGuid>0d59f60a-75bd-4863-8de5-5d897346eb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal fall protection equipment'])[1]/following::div[12]</value>
      <webElementGuid>2f7e5b06-0440-47ef-a61f-4da61be068b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anchor points'])[1]/preceding::div[5]</value>
      <webElementGuid>52009cec-daef-497f-a081-3d030f3d8150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-requirements-input[9]/div/div/app-accordion/div/div</value>
      <webElementGuid>32a4e6d1-d020-4627-85c9-f4d502d0c348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '9.2.2Personal fall protection equipment' or . = '9.2.2Personal fall protection equipment')]</value>
      <webElementGuid>ba2df37f-2d5a-4353-bb6e-46175d904638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
