<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-error_Mandatory information missing</name>
   <tag></tag>
   <elementGuidId>af6a0dfb-311c-4332-8b45-46bc15c1a058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-error-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-error-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>065f8f7c-f79d-4844-bc6e-a27bcd7c8db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3299b9a-b064-4e8a-be7e-ddc4a8fb34d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-error error-scroll</value>
      <webElementGuid>5f153912-680a-4ccc-b61e-1249752f3284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>b3a4b1b2-babb-4e07-9eee-d028f4ceb862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-error-1</value>
      <webElementGuid>1d3e0018-215b-4248-ad31-f189030cf73b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mandatory information missing </value>
      <webElementGuid>546764db-bb38-4c3d-8fa0-4e5c2665200d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-error-1&quot;)</value>
      <webElementGuid>ec376daa-fd8a-46c9-95fa-305579715872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-error-1']</value>
      <webElementGuid>bae91407-e7d1-4a6d-9e00-5a77807507c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-tab[@id='reqs-tab']/div/div/app-requirements-section-list/app-requirements-input[2]/div/div/mat-error</value>
      <webElementGuid>1fafa2f9-6bf8-40c2-94ac-ffacb19b9f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rights and Responsibilities'])[1]/following::mat-error[1]</value>
      <webElementGuid>015df30b-1424-4ddd-b886-77f5f8b5ed15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expand all'])[2]/following::mat-error[1]</value>
      <webElementGuid>99da358d-4176-461f-9f1f-cc82efa077f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification of the hazards of working at heights'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>50582bd5-7f7b-4eeb-8a36-c06d21b389c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandatory information missing'])[3]/preceding::mat-error[1]</value>
      <webElementGuid>c045d9b1-5dd3-49f4-8bc6-9e5b86cc3337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-requirements-input[2]/div/div/mat-error</value>
      <webElementGuid>2931e080-631f-40b9-abd2-248c61e0ad66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-error-1' and (text() = 'Mandatory information missing ' or . = 'Mandatory information missing ')]</value>
      <webElementGuid>8e772066-c400-4c46-8292-8d15c3ca6019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
