<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SepSun11 In-Class Software DevelopmentT_614cdf</name>
   <tag></tag>
   <elementGuidId>65aab691-2962-4c73-afda-3a983c1b75ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div/div[10]/div[4]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37bc828d-d86a-454e-ba2b-81c2999b75cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tile-container ontario-column ontario-small-12 ontario-medium-12 ontario-large-4</value>
      <webElementGuid>ccd68832-17df-4925-9e6a-5007d3bde59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SepSun11 In-Class Software DevelopmentTEST - Jaclyn's amazing trainingTraining LocationTEST - 123 Street, TEST - Toronto, ON, T0T 0T0Class information Sep 11 - Sun @ 4:00 PM to 8:15 PM Aug 7 - Sun @ 1:30 PM to 3:30 PMSeats available0/20Course Fee$400.00</value>
      <webElementGuid>ee952918-3dbc-4b41-948f-654dc666dc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-homepage[1]/app-tabs[1]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-marketplace[1]/div[@class=&quot;ontario-row&quot;]/div[@class=&quot;button-row ontario-column ontario-small-12&quot;]/div[@class=&quot;marketplace-tile-row selected-view&quot;]/div[@class=&quot;schedule-container ontario-row&quot;]/div[@class=&quot;tile-container ontario-column ontario-small-12 ontario-medium-12 ontario-large-4&quot;]</value>
      <webElementGuid>71b97374-2796-4175-ac00-0013c584001d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div/div[10]/div[4]/div/div[3]</value>
      <webElementGuid>bf5fd800-513d-45bd-9db4-06907f054a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact us'])[1]/following::div[1]</value>
      <webElementGuid>d356c2fa-0060-4b68-8503-f5c53b5a2744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Course Fee'])[2]/following::div[1]</value>
      <webElementGuid>9490c477-3a33-4b29-8cb5-90c03a6deda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]</value>
      <webElementGuid>d7e05cc4-dd48-44d8-973f-f6f4d8786fad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;SepSun11 In-Class Software DevelopmentTEST - Jaclyn&quot; , &quot;'&quot; , &quot;s amazing trainingTraining LocationTEST - 123 Street, TEST - Toronto, ON, T0T 0T0Class information Sep 11 - Sun @ 4:00 PM to 8:15 PM Aug 7 - Sun @ 1:30 PM to 3:30 PMSeats available0/20Course Fee$400.00&quot;) or . = concat(&quot;SepSun11 In-Class Software DevelopmentTEST - Jaclyn&quot; , &quot;'&quot; , &quot;s amazing trainingTraining LocationTEST - 123 Street, TEST - Toronto, ON, T0T 0T0Class information Sep 11 - Sun @ 4:00 PM to 8:15 PM Aug 7 - Sun @ 1:30 PM to 3:30 PMSeats available0/20Course Fee$400.00&quot;))]</value>
      <webElementGuid>b1a44d8a-562b-458f-aa02-8ace3dc4cede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
