<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Total seats_numeric-input-div</name>
   <tag></tag>
   <elementGuidId>08c27902-cab3-4cff-9608-91f87da77477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.grow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c21011cd-130c-40c7-9677-68263450f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grow</value>
      <webElementGuid>36c246a5-d626-4361-8057-4062c82868a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/header[1]/div[@class=&quot;primary-row&quot;]/div[@class=&quot;container&quot;]/div[1]/div[@class=&quot;grow&quot;]</value>
      <webElementGuid>bfb733b3-fadd-4653-895b-e2a221d6b265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>3b2d9699-d33f-4b71-b9a5-6fa71efd8da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div/div[9]/app-numeric-input/div/div</value>
      <webElementGuid>73d2956d-d085-43a7-bb5e-6fb5bcc120c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total seats'])[1]/following::div[1]</value>
      <webElementGuid>df199b87-ed22-411d-8c51-505fd1ed314b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To date'])[1]/following::div[4]</value>
      <webElementGuid>20ed82ea-9074-44a1-a4aa-4353a0c0ba78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show the listings with course fee only'])[1]/preceding::div[1]</value>
      <webElementGuid>73dc9df9-e4e9-4606-8783-d5a837276698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekend classes only'])[1]/preceding::div[3]</value>
      <webElementGuid>343c45c2-a02f-4352-87ba-4c68031277f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-numeric-input/div/div</value>
      <webElementGuid>1155dc76-2022-4721-a9ab-75b2006ceb6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
