<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Franais</name>
   <tag></tag>
   <elementGuidId>55bf949a-b920-4f04-9ae8-7f73001650d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='MLITSD CPO Approved Training Courses'])[1]/preceding::div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2caa93f9-b12d-4446-8817-4e7567f9f98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container</value>
      <webElementGuid>753d5194-e85c-4966-a18b-b5570f23aa72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Français</value>
      <webElementGuid>246812d6-0c63-4b48-b25c-3fcc96e107b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/header[1]/div[@class=&quot;primary-row&quot;]/div[@class=&quot;container&quot;]</value>
      <webElementGuid>ae1dbfc0-8f0d-49ed-aa58-fe91a17e6ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MLITSD CPO Approved Training Courses'])[1]/preceding::div[4]</value>
      <webElementGuid>34105442-c47c-48e9-8438-84a44e52c353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>6500a061-fea8-4c2e-9a8d-ed05b1e6524b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Français' or . = 'Français')]</value>
      <webElementGuid>b092739d-73d8-44d3-97d8-391af4cb1d1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
