<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Training Program All Safety Training Pr_fda766</name>
   <tag></tag>
   <elementGuidId>c1c69223-b31f-468e-89fb-6b47afae8460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-marketplace > div.ontario-row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eb88783a-8211-43a1-a928-1740966e08a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-row</value>
      <webElementGuid>983cfa60-2802-4b92-beaf-b9482e3a7992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training Program All Safety Training ProgramsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights - FullWorking at Heights - RefresherTraining providerTraining typeAllBlendedDistanceeLearningIn-ClassTraining locationSelect radiusAll25 kms50 kms100 kms From date  To dateTotal seatsShow the listings with course fee onlyWeekend classes onlySearchReset filtersSort by Date: Earliest - LatestDate: Latest - EarliestPrice: Low - HighPrice: High - LowShowing 0 course advertisementsFeedback We would like to hear about your experience and welcome suggestions/feedback to improve the service. </value>
      <webElementGuid>8e4260ff-f54e-4dc6-ac13-f0882998b64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-homepage[1]/app-tabs[1]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-marketplace[1]/div[@class=&quot;ontario-row&quot;]</value>
      <webElementGuid>48364c7d-3587-43d2-a6b9-513ad54695b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div</value>
      <webElementGuid>db2c77db-f3e7-4ccf-936b-7aac1a51a61e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approved Training Providers'])[1]/following::div[5]</value>
      <webElementGuid>01da62ac-d6f6-479a-aafe-0cfd3b2bc369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training Eligibility'])[1]/following::div[5]</value>
      <webElementGuid>befd8de5-8ceb-45ea-b591-160371acb335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-marketplace/div</value>
      <webElementGuid>b048e9bc-3db5-422f-86f1-e83572e4f82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Training Program All Safety Training ProgramsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights - FullWorking at Heights - RefresherTraining providerTraining typeAllBlendedDistanceeLearningIn-ClassTraining locationSelect radiusAll25 kms50 kms100 kms From date  To dateTotal seatsShow the listings with course fee onlyWeekend classes onlySearchReset filtersSort by Date: Earliest - LatestDate: Latest - EarliestPrice: Low - HighPrice: High - LowShowing 0 course advertisementsFeedback We would like to hear about your experience and welcome suggestions/feedback to improve the service. ' or . = 'Training Program All Safety Training ProgramsJHSC - Part OneJHSC - Part TwoJHSC - RefresherWorking at Heights - FullWorking at Heights - RefresherTraining providerTraining typeAllBlendedDistanceeLearningIn-ClassTraining locationSelect radiusAll25 kms50 kms100 kms From date  To dateTotal seatsShow the listings with course fee onlyWeekend classes onlySearchReset filtersSort by Date: Earliest - LatestDate: Latest - EarliestPrice: Low - HighPrice: High - LowShowing 0 course advertisementsFeedback We would like to hear about your experience and welcome suggestions/feedback to improve the service. ')]</value>
      <webElementGuid>9d1f339b-2b71-46dc-9da9-8e57ad263b46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
