<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Ministry of Labour, Training and Skills _ca15bc</name>
   <tag></tag>
   <elementGuidId>0b94ba36-997b-4c89-8fbe-ef9af922a1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ministry-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='ministry-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fb838a1d-00eb-47e5-b714-f8f4c74c72f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ministry-title</value>
      <webElementGuid>9f154eb0-9e5d-466b-b08c-068d786f98ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-h4</value>
      <webElementGuid>449f0489-2351-449f-aef7-a358f13b01a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ministry of Labour, Training and Skills Development </value>
      <webElementGuid>0e38c12b-ae6d-4b6f-8101-0d1d98d74c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ministry-title&quot;)</value>
      <webElementGuid>fc799940-f32f-439b-8197-2af40e4f7c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='ministry-title']</value>
      <webElementGuid>43e4b881-97f5-488b-b57a-2736f866a40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feedback'])[1]/following::h2[1]</value>
      <webElementGuid>381d86f7-c005-4f5e-bb36-311e0aea9bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 0 course advertisements'])[1]/following::h2[1]</value>
      <webElementGuid>2e9e81b6-f149-4cb6-af33-bee36278487e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Ontario'])[1]/preceding::h2[1]</value>
      <webElementGuid>44d8a375-06a0-4e5e-b12b-6cbb269d79b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::h2[1]</value>
      <webElementGuid>b0de769e-a2ae-4443-a28c-1a5223c37405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ministry of Labour, Training and Skills Development']/parent::*</value>
      <webElementGuid>2e04f39b-730e-4530-aedc-df787943a159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>54526f1d-a42f-4f5f-8c6d-27b61676b766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'ministry-title' and (text() = 'Ministry of Labour, Training and Skills Development ' or . = 'Ministry of Labour, Training and Skills Development ')]</value>
      <webElementGuid>5e49fecc-4d8e-420c-a74c-dbfb593a5ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
