<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Showing 7 course advertisements</name>
   <tag></tag>
   <elementGuidId>cb0d3dfb-ecd6-42e0-ae7a-ca123d1674d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#results-count</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='results-count']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72de3a6d-2f28-42be-8287-704393fa7a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>results-count</value>
      <webElementGuid>413b132a-fa85-4d9f-b0ad-d0fe0fd6ac04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 7 course advertisements</value>
      <webElementGuid>8c8dacf8-f346-4884-ab56-e7cafc066fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results-count&quot;)</value>
      <webElementGuid>7f552126-0ef1-473c-a398-0643c0466607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>77b5fcc1-eb8e-4b63-b746-95456559c723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>results-count</value>
      <webElementGuid>9488765e-1a08-4fb5-9ebb-fdde2895d27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 7 course advertisements</value>
      <webElementGuid>02bc0330-f62d-4b22-8d99-abaace4a0067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;results-count&quot;)</value>
      <webElementGuid>766bc3c3-b0c4-4346-b3bd-60bd49b41e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='results-count']</value>
      <webElementGuid>e97bc418-3eff-4eee-b49b-a7eb26f9083f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-homepage/app-tabs/div/div[2]/app-marketplace/div/div[10]/div[3]/span</value>
      <webElementGuid>ebb75096-e02c-4e0e-8675-5acd7d2c697d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort by'])[1]/following::span[3]</value>
      <webElementGuid>b4965c26-6b29-4f67-8855-9f3aa18ed5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset filters'])[1]/following::span[3]</value>
      <webElementGuid>da8d1d9c-0ec6-4fad-a0d0-1254cf3edd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In-Class'])[2]/preceding::span[1]</value>
      <webElementGuid>cc4874be-6abd-4252-83eb-e726b200533a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='July'])[1]/preceding::span[1]</value>
      <webElementGuid>4c144958-572b-41bd-ad71-b13329513ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 7 course advertisements']/parent::*</value>
      <webElementGuid>bb5cb329-4c6a-41ff-aba0-f1f162bb75d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span</value>
      <webElementGuid>cf41646f-8a64-4137-b64e-47854973cf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'results-count' and (text() = 'Showing 7 course advertisements' or . = 'Showing 7 course advertisements')]</value>
      <webElementGuid>13e2b5b9-505c-4e77-aaf0-2ec038041e09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
