<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Preview classroom (1)</name>
   <tag></tag>
   <elementGuidId>6d109558-286d-4c16-9d63-f83dbbc403ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#preview-class</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='preview-class']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>db470988-919b-43ac-b045-bed33b751a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>preview-class</value>
      <webElementGuid>80fe61e1-d12b-412d-b2c1-ee650f6063e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blue-button ng-star-inserted</value>
      <webElementGuid>ac6c0893-e70f-4962-9c94-e1eaf6401e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Preview classroom </value>
      <webElementGuid>8638a03f-f09f-446c-9219-569bb9c092d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;preview-class&quot;)</value>
      <webElementGuid>19a9343c-e656-4a5d-85f3-5d6fd6d42fac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='preview-class']</value>
      <webElementGuid>71a82c3e-5265-4ca9-ad41-d18681b9b756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-create-classroom/div[3]/div/div/button[2]</value>
      <webElementGuid>b2bafb34-21de-48d4-a585-5a031ae4ed54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::button[1]</value>
      <webElementGuid>52f3a988-2da1-4a5c-bb81-fc583022c308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications for this classroom'])[1]/following::button[2]</value>
      <webElementGuid>9126966c-6565-42c5-a48b-7c29808367e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ministry of Labour, Immigration, Training and Skills Development'])[1]/preceding::button[1]</value>
      <webElementGuid>f807c37a-8534-47f4-9272-168f1264a9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Ontario'])[1]/preceding::button[1]</value>
      <webElementGuid>2419cc77-7ab5-4176-a383-ba83673ac8f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preview classroom']/parent::*</value>
      <webElementGuid>410191f8-7b42-4d33-a44d-3864f56df843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>b4718dd2-02e9-47d8-80bb-f09ad6d192f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'preview-class' and (text() = ' Preview classroom ' or . = ' Preview classroom ')]</value>
      <webElementGuid>c22c92ca-8729-4190-94a4-f7da3bbd121e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
