<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Street AddressCityTownProvincePlease se_91aa4d (1)</name>
   <tag></tag>
   <elementGuidId>06a34f6f-d903-4682-b753-66db7558f575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/app-create-classroom/div[2]/div[2]/app-tabs/div/div[2]/app-tab/div/div/div[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebe07b05-32b3-4832-93d2-fb17a515b30f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content ng-star-inserted</value>
      <webElementGuid>da8eace0-15ff-49e4-8d75-7cacffe831dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Street AddressCity/TownProvincePlease select province/stateABBCMBNBNLNSNTNUONPEQCSKYTPostal CodeMake this as a favourite location</value>
      <webElementGuid>e539f648-88da-4860-a361-f7f9e3181bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-create-classroom[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ontario-row ontario-margin-top-32-! ontario-padding-bottom-24-!&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-margin-top-16-!&quot;]/app-tabs[1]/div[@class=&quot;ontario-tabs&quot;]/div[@class=&quot;ontario-tab-content&quot;]/app-tab[1]/div[@class=&quot;tab&quot;]/div[@class=&quot;ontario-small-12 ontario-large-6 training-schedule-div ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;content ng-star-inserted&quot;]</value>
      <webElementGuid>e4348bb7-07d2-4f85-913f-8f0ed8528e23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-create-classroom/div[2]/div[2]/app-tabs/div/div[2]/app-tab/div/div/div[7]</value>
      <webElementGuid>e9a4a6e4-bf81-4bf2-a1e0-d02bed568b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training location'])[1]/following::div[1]</value>
      <webElementGuid>2d36b1d2-6369-425d-8eba-391d4e4e3af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recurring meeting'])[1]/following::div[2]</value>
      <webElementGuid>e7bf8b01-69f9-49c7-83ee-6b2640ccf253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]</value>
      <webElementGuid>e964a27c-cede-4751-a47e-71d6608ddd4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Street AddressCity/TownProvincePlease select province/stateABBCMBNBNLNSNTNUONPEQCSKYTPostal CodeMake this as a favourite location' or . = 'Street AddressCity/TownProvincePlease select province/stateABBCMBNBNLNSNTNUONPEQCSKYTPostal CodeMake this as a favourite location')]</value>
      <webElementGuid>b56dc0c5-1438-4bb0-8197-0b2c8bb0ab36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
