<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You can appoint your team member to com_9e5747</name>
   <tag></tag>
   <elementGuidId>a7bb1ee6-caf9-4dc0-85c9-bf34dbd9cb20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#teamMember > div.box > div.box-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-add-team-member[@id='teamMember']/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76260a58-02c5-48bf-99fc-bbd31d4d28b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-body</value>
      <webElementGuid>48e7ea29-b517-426d-a528-fd0f71288612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You can appoint your team member to complete the program delivery application on your behalf. System will send an invitation email to your team member to setup the account. You will be able to add team members with different access permission later.First nameLast namePhone number Email addressTeam member's role in organization/company Select a roleManager / Senior LeadershipHealth and Safety CoordinatorHealth and Safety Program DeveloperCoordinator of Training ActivitiesHuman ResourcesInstructorAdministrative Support Cancel </value>
      <webElementGuid>21369218-0b69-41c1-ba1d-8e5d08c0db53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teamMember&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]</value>
      <webElementGuid>339aace4-a6ea-4db9-93e5-dd6e8dd8b317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c1d8b54-ba94-4889-9aa1-aa46d9d89dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-body</value>
      <webElementGuid>1ef38ee6-4a10-4eb4-8e22-e94dc4f61241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You can appoint your team member to complete the program delivery application on your behalf. System will send an invitation email to your team member to setup the account. You will be able to add team members with different access permission later.First nameLast namePhone number Email addressTeam member's role in organization/company Select a roleManager / Senior LeadershipHealth and Safety CoordinatorHealth and Safety Program DeveloperCoordinator of Training ActivitiesHuman ResourcesInstructorAdministrative Support Cancel </value>
      <webElementGuid>c4882ab4-9e15-4e9c-bce2-59cc554157f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;teamMember&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;box-body&quot;]</value>
      <webElementGuid>8005681b-111e-4618-8e29-0ead7c725479</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-add-team-member[@id='teamMember']/div/div[2]</value>
      <webElementGuid>a522ec25-e123-44e9-8c35-e3d415ad5621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a team member on your account (Optional)'])[1]/following::div[1]</value>
      <webElementGuid>0bc7c85f-f1d4-4b7d-950f-ad9a07240302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::div[3]</value>
      <webElementGuid>7231b235-81be-43ad-9463-a52ac7f0fe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-add-team-member/div/div[2]</value>
      <webElementGuid>6ef0a9b2-e332-4f9d-8504-f55bee181996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;You can appoint your team member to complete the program delivery application on your behalf. System will send an invitation email to your team member to setup the account. You will be able to add team members with different access permission later.First nameLast namePhone number Email addressTeam member&quot; , &quot;'&quot; , &quot;s role in organization/company Select a roleManager / Senior LeadershipHealth and Safety CoordinatorHealth and Safety Program DeveloperCoordinator of Training ActivitiesHuman ResourcesInstructorAdministrative Support Cancel &quot;) or . = concat(&quot;You can appoint your team member to complete the program delivery application on your behalf. System will send an invitation email to your team member to setup the account. You will be able to add team members with different access permission later.First nameLast namePhone number Email addressTeam member&quot; , &quot;'&quot; , &quot;s role in organization/company Select a roleManager / Senior LeadershipHealth and Safety CoordinatorHealth and Safety Program DeveloperCoordinator of Training ActivitiesHuman ResourcesInstructorAdministrative Support Cancel &quot;))]</value>
      <webElementGuid>ced63bc7-d7a8-4910-9e3a-ae75453037d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
