<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Other MLTSD Programs</name>
   <tag></tag>
   <elementGuidId>e5c9833e-814b-4279-a7d9-7c486ec6b959</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='otherMLTSDPrograms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#otherMLTSDPrograms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>e151c849-1e1f-4343-915c-c9aa7f021802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherMLTSDPrograms</value>
      <webElementGuid>70b472a4-5429-48a8-8df4-9f6de48609e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other MLTSD Programs</value>
      <webElementGuid>c635e41f-ad6d-4a87-a870-d98531b457d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherMLTSDPrograms&quot;)</value>
      <webElementGuid>5d672a31-9884-4483-bb33-c918d3f5a383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>89800cba-cbc4-43ad-a168-b5b5e69dac3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>otherMLTSDPrograms</value>
      <webElementGuid>74155f15-1314-47f2-af54-bca960fbfc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Other MLTSD Programs</value>
      <webElementGuid>3a536884-4de2-4943-b9f4-47a7537bbeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;otherMLTSDPrograms&quot;)</value>
      <webElementGuid>a4040034-b982-4818-8448-d3f80f65b448</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='otherMLTSDPrograms']</value>
      <webElementGuid>169f3b1d-9011-4afd-ac34-10b60f50c169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trainingDeliveryInfo']/h3[2]</value>
      <webElementGuid>64cc5112-3658-44c2-a46d-6b991880bc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[2]/following::h3[1]</value>
      <webElementGuid>5ebfa44a-3315-4a36-a5f9-0f62c395de1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[2]/following::h3[1]</value>
      <webElementGuid>c879c0b5-3ed3-4483-80ba-0b8e4fd60856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::h3[1]</value>
      <webElementGuid>4f1053c8-9cd6-449c-9e4f-b134416341d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[3]/preceding::h3[1]</value>
      <webElementGuid>a18d4e81-7ce1-449c-8b66-0af6087e7c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Other MLTSD Programs']/parent::*</value>
      <webElementGuid>024020c4-4219-4f6a-be5d-fe0644fe1747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3[2]</value>
      <webElementGuid>5962688c-fcfd-4fa0-8671-16f375dd174e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'otherMLTSDPrograms' and (text() = 'Other MLTSD Programs' or . = 'Other MLTSD Programs')]</value>
      <webElementGuid>b88b565c-0e45-4a1c-a935-a063e263945a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
