<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Add alternate signing authority (option_8aa542</name>
   <tag></tag>
   <elementGuidId>53158a97-43db-432e-a46a-2e7beeb19f9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='accordian-id1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accordian-id1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>93c32334-8fb7-4396-8669-1da28374204d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordian-id1</value>
      <webElementGuid>0ad5a07c-e785-4c2c-a9a8-b23807139ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/circled-plus-black.svg</value>
      <webElementGuid>80f2b25b-ff41-4ab5-a078-3cb539597ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alternateSigningAuthority&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;box-header signingAuthorityExpender&quot;]/h3[1]/img[@id=&quot;accordian-id1&quot;]</value>
      <webElementGuid>636df03f-7892-458a-885a-5149a5e0fac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ce45d13-5541-43f4-a5db-14442d1c6348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordian-id1</value>
      <webElementGuid>7a0615f1-641e-4c4e-a700-f488fe740238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/circled-plus-black.svg</value>
      <webElementGuid>0c1775c9-f2fc-4a9b-8059-30d26bdbe6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alternateSigningAuthority&quot;)/div[@class=&quot;box&quot;]/div[@class=&quot;box-header signingAuthorityExpender&quot;]/h3[1]/img[@id=&quot;accordian-id1&quot;]</value>
      <webElementGuid>2e69e41d-cbb1-43aa-96d4-76f3fb9d89a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='accordian-id1']</value>
      <webElementGuid>9f22bb16-f534-4f99-ad88-4df7d795b15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-alt-signing-authority-information[@id='alternateSigningAuthority']/div/div/h3/img</value>
      <webElementGuid>96a90dd7-abe5-434f-9156-b75302784ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/img</value>
      <webElementGuid>eaf0eeca-cec8-434d-92e4-cc80c26f190e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'accordian-id1' and @src = 'assets/images/circled-plus-black.svg']</value>
      <webElementGuid>f351b87d-8581-40c6-9a60-24cebb8408a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
