<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__radio-buttons-0.5204258864639253-0</name>
   <tag></tag>
   <elementGuidId>71e9f6c1-a70d-4a58-be07-73c82b65c2bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-button-option-0.5204258864639253-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8109619a-2278-4f36-b5b1-d4218b08a060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6f584789-1373-4ce7-addc-3aa8b617fc0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ontario-radios__input</value>
      <webElementGuid>bc0bf75a-f887-4bb9-8769-fc3778319022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-button-option-0.5204258864639253-0</value>
      <webElementGuid>8d1174e4-1ed7-4cba-9d53-c3ab7b76e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-buttons-0.5204258864639253-0</value>
      <webElementGuid>6795f48c-120c-47d4-a898-a0a3eb87aaf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c1d5bd46-40d6-41b3-86a3-ac042a56b1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-button-option-0.5204258864639253-0&quot;)</value>
      <webElementGuid>50cee773-1ae4-4c54-a819-5ce880bd44f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-button-option-0.5204258864639253-0']</value>
      <webElementGuid>139a3dff-e665-4e11-802e-f52bc78aad2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trainingDeliveryInfo']/div[2]/div/div[3]/app-radio-button-list/div[2]/input</value>
      <webElementGuid>a2c51d39-4901-4af0-989f-e9cd5d6519f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/app-radio-button-list/div[2]/input</value>
      <webElementGuid>6f424a9a-815a-410e-9457-bade6934ec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio-button-option-0.5204258864639253-0' and @name = 'radio-buttons-0.5204258864639253-0']</value>
      <webElementGuid>f393d2e1-6027-4ef3-ad03-79fd0440802d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
