<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Business primary address</name>
   <tag></tag>
   <elementGuidId>cf13c8b3-8692-4c69-acb8-987163948578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessInformation > div.ontario-row.input-div > div.ontario-column.ontario-small-12.ontario-large-12 > form.ng-untouched.ng-pristine.ng-invalid > div.row.ontario-row > div.tp-input-row.ontario-small-12.ontario-medium-6.ontario-column.ontario-large-5.dropdown-col.mailing-dropdown.first > mat-label.input-label > span.required-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-business-information[@id='businessInformation']/div/div/form/div[6]/div/mat-label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3fd25801-0be0-4d11-8e50-bfed0e47ffbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>9da60915-b203-4c93-a838-8e320f3ace17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business primary address</value>
      <webElementGuid>84ed8e57-fcca-42ad-9cc1-8619f8f7e3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessInformation&quot;)/div[@class=&quot;ontario-row input-div&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-12&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row ontario-row&quot;]/div[@class=&quot;tp-input-row ontario-small-12 ontario-medium-6 ontario-column ontario-large-5 dropdown-col mailing-dropdown first&quot;]/mat-label[@class=&quot;input-label&quot;]/span[@class=&quot;required-field&quot;]</value>
      <webElementGuid>6f254b5a-f088-4f23-9d1c-131d93273519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>911d8b23-85e9-4886-a353-7be8dd61e4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-field</value>
      <webElementGuid>1f09e1be-8950-44f1-8558-279baaf8f1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Business primary address</value>
      <webElementGuid>206b549e-6378-425b-91de-94eb6092ea87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessInformation&quot;)/div[@class=&quot;ontario-row input-div&quot;]/div[@class=&quot;ontario-column ontario-small-12 ontario-large-12&quot;]/form[@class=&quot;ng-untouched ng-pristine ng-invalid&quot;]/div[@class=&quot;row ontario-row&quot;]/div[@class=&quot;tp-input-row ontario-small-12 ontario-medium-6 ontario-column ontario-large-5 dropdown-col mailing-dropdown first&quot;]/mat-label[@class=&quot;input-label&quot;]/span[@class=&quot;required-field&quot;]</value>
      <webElementGuid>0f2b8767-cf99-4a36-afba-19a3e46672f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//app-business-information[@id='businessInformation']/div/div/form/div[6]/div/mat-label/span</value>
      <webElementGuid>39c48fc2-3651-4cab-9666-10e1fa0fb677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WSIB Account Number'])[1]/following::span[1]</value>
      <webElementGuid>0134c390-e0b4-4cb6-a6ce-0c1a07229cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Type'])[1]/following::span[2]</value>
      <webElementGuid>cd06c642-1da0-4870-9629-7f5736d7f827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company website'])[1]/preceding::span[1]</value>
      <webElementGuid>725e9772-6be6-4718-a5b9-308e7c3e7ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Preferred method of correspondence'])[1]/preceding::span[1]</value>
      <webElementGuid>c2382ecd-d63c-449b-8b99-af22cd15acd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Business primary address']/parent::*</value>
      <webElementGuid>1cc6da9c-0fe4-405a-83fa-f31f5f379e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/mat-label/span</value>
      <webElementGuid>50b8d6b5-6d5b-44b7-814c-1c230d03457d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Business primary address' or . = 'Business primary address')]</value>
      <webElementGuid>1d201c63-4dbb-49cb-bff7-97b904d3c7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
