<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TEST - Jaclyns amazing training</name>
   <tag></tag>
   <elementGuidId>163f22f5-fdbc-4c34-b3ea-3a036a91155b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#provider-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='provider-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11fd00fe-6350-4a34-b7c9-ad39c77fce0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>provider-name</value>
      <webElementGuid>b4fe8c9e-a8d9-4a35-b964-aecef41e97df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>column-val</value>
      <webElementGuid>ae69a839-cd34-43fa-b8ea-f37cd31a6221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TEST - Jaclyn's amazing training</value>
      <webElementGuid>1fab7402-1361-4359-a7c5-a92fa5321770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;provider-name&quot;)</value>
      <webElementGuid>fc9094a1-86b2-45b5-b7f7-74f6866157b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='provider-name']</value>
      <webElementGuid>1868bbed-c583-450c-87cd-8f4f191a5a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/app-safety-and-prevention-homepage/app-tabs/div/div[2]/app-safety-and-prevention/div/div[2]/div[5]/div/div/div/div</value>
      <webElementGuid>07586d7e-ac1d-466f-8b8c-c4dbf6f18697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider name'])[1]/following::div[1]</value>
      <webElementGuid>190c617e-a5c4-4615-aa5c-cc8f088acb1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access all CPO-approved providers'])[1]/following::div[5]</value>
      <webElementGuid>4bfee488-105a-46cb-b034-93be6bf7aced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registered address'])[1]/preceding::div[1]</value>
      <webElementGuid>be3ac644-cfa5-4791-986e-7dcee1267308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N/A'])[1]/preceding::div[1]</value>
      <webElementGuid>f8ac0e0b-24c6-4b8b-bdcc-e5e1834c82a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div</value>
      <webElementGuid>2fad6b5a-fb7c-42fc-a68b-97874afb9bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'provider-name' and (text() = concat(&quot; TEST - Jaclyn&quot; , &quot;'&quot; , &quot;s amazing training&quot;) or . = concat(&quot; TEST - Jaclyn&quot; , &quot;'&quot; , &quot;s amazing training&quot;))]</value>
      <webElementGuid>2a5f56f8-ecff-43ca-b3bd-41713c83c947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
