<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dont have an accountCreate AccountORSig_fe4b2d (1)</name>
   <tag></tag>
   <elementGuidId>31b69cb3-7b97-426d-9136-6700a71fdfc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='okta-sign-in']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e79cf5c9-8cd1-4cc5-9423-5e700d63e5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-content</value>
      <webElementGuid>0bba883b-1713-4e15-88d2-868a29d56398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Don't have an account?Create AccountORSign in to My Ontario AccountEmail The email address you registered withPassword Remember meORSign-In PartnerNeed help signing in?Forgot password?Unlock account?Expired account activation link?</value>
      <webElementGuid>5d03e637-efec-4031-bdc5-b71bbeaec15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okta-sign-in&quot;)/div[@class=&quot;auth-content&quot;]</value>
      <webElementGuid>f05fead3-1655-4c64-96ee-431e935d2c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='okta-sign-in']/div[2]</value>
      <webElementGuid>051e1483-c575-4be4-8870-95bf3767ddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Français'])[1]/following::div[9]</value>
      <webElementGuid>66d6d204-5204-408c-90c6-adc6f331d0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FR'])[1]/following::div[9]</value>
      <webElementGuid>841438fc-a7ba-4a58-b9ef-d8306020770c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]</value>
      <webElementGuid>58cd3406-e10a-4d71-9d2c-0e23244d0220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t have an account?Create AccountORSign in to My Ontario AccountEmail The email address you registered withPassword Remember meORSign-In PartnerNeed help signing in?Forgot password?Unlock account?Expired account activation link?&quot;) or . = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t have an account?Create AccountORSign in to My Ontario AccountEmail The email address you registered withPassword Remember meORSign-In PartnerNeed help signing in?Forgot password?Unlock account?Expired account activation link?&quot;))]</value>
      <webElementGuid>67a371ea-0c7b-47c3-9d5c-080bfc63de92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
