<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_password (11)</name>
   <tag></tag>
   <elementGuidId>1afb2c95-928f-467c-9aa5-3a59faa9289e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#okta-signin-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okta-signin-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85be1903-404b-4b0c-a496-0129975250e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ed076904-cf4f-4217-a5a6-a2512527b056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a579bebf-8588-402a-b137-32e78b1e949c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okta-signin-password</value>
      <webElementGuid>c1b38047-4434-4fd5-b203-d4269215d260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>5e23a7a3-af63-4731-ac46-2f2105ed0f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password-with-toggle</value>
      <webElementGuid>5a9b7e80-bd1e-49b0-b690-edd04fb331f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>603feb80-bb05-46c9-85e5-754b0987f0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc927a30-6bb4-472a-8c92-3f59271d1d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okta-signin-password&quot;)</value>
      <webElementGuid>df28cfb9-ab0e-467d-a042-d1e3d54fa758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okta-signin-password']</value>
      <webElementGuid>d3f3674e-efe5-4ac7-8056-f08dc8b7baef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form32']/div/div[4]/div[2]/div[2]/span/input</value>
      <webElementGuid>1ddb7406-2fc0-47e1-9fe7-e457db30a7ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>ffa9f249-6be3-4b64-9add-29b7dbcc1e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'password' and @id = 'okta-signin-password']</value>
      <webElementGuid>953fe963-dde2-4be8-852d-e5984a79ac0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
